<?php
$menuu_array=array();
$menuu_array["menuu"]="Menu";
$menuu_array["keel"]=$keel;
$menuu_array["menuu_01"]="Index";
$menuu_array["menuu_02"]="Projects";
$menuu_array["menuu_03"]="Programming";
$menuu_array["menuu_04"]="HTML";
$menuu_array["menuu_05"]="Mp3";
$menuu_array["menuu_06"]="Doom";
$menuu_array["menuu_07"]="Links";
$menuu_array["menuu_08"]="Download";
$menuu_array["menuu_09"]="Serialz";
$menuu_array["menuu_10"]="Questbook";
$menuu_array["menuu_11"]="Contact";
$menuu_array["menuu_12"]="Films";
$menuu_array["menuu_13"]="Games";
$menuu_array["menuu_14"]="Programs";
?>