<table cellpadding="5" border="0">
<tr><td class="text">
Doom on umbes 10 aastat vana mäng. Kuid vaatamata oma vanusele, ning sellele et
varsti välja tulemas Doom 3, mängitakse seda ikka veel. Mängitakse võrgus läbi interneti.
Populaarsemad vahendid doomi mängimiseks on Doom Legacy ja Zdaemon.
</td></tr>
<tr><td class="text">
<b>Lingid</b><br><br>
<li><a href="http://www.xodemultimedia.com/connector_download.php" class="text">Doom Connector</a> - Vajalik võrgus doomi mängimiseks.</li>
<li><a href="http://legacy.newdoom.com/dl_lega.shtml" class="text">Legacy</a></li>
<li><a href="http://www.zdaemon.org" class="text">Zdaemon</a></li>
</td></tr>
<tr><td class="text">
<b>Vajalikud failid</b><br><br>
<li><a href="doom/doom.zip" class="text">Doom.wad</a> - Doom I</li>
<li><a href="doom/doom1.zip" class="text">Doom1.wad</a> - Shareware Doom</li>
<li><a href="doom/doom2.zip" class="text">Doom2.wad</a> - Doom II</li>
<li><a href="http://www.zone.ee/cljim/tnt.zip" class="text">tnt.wad</a> - Doom Evilution(Final Doom)</li>
<li><a href="http://www.zone.ee/cljim/plutonia.zip" class="text">plutonia.wad</a> - Doom Plutonia(Final Doom)</li>
</td></tr>
</table>