<table cellpadding="5" border="0">
<tr><td class="text">
Max on jutukates kasutatav trivia bot(robot), mis põhineb mirc'i scriptil(Kasutab mirc versiooni 6.01).
Praeguseks on trivia küsimusi juba üle 500 ning neid saab juurde lisada.
Probleemide tekkimisel saata mail: <a href="mailto:jc@starline.ee" class="text">jc@starline.ee</a>.
</td></tr>
<tr><td class="text">
<b>Versioon 1.1 sisaldab:</b><br><br>
<li>mirc 6.01.</li>
<li>punktid2html.exe - programm punktidest html nimekirja tegemiseks.</li>
<li>500 küsimust</li>
</td></tr>
<tr><td class="text">
<b>Tõmbamine:</b><br><br>
<li><a href="max/max_1_1_setup.exe" class="text">max_1_1_setup.exe</a> - win32 installer.</li>
<li><a href="max/max_1_1.zip" class="text">max_1_1.zip</a> - winzipi'ga pakitud failid.</li>
</td></tr>
</table>