<?php
$menuu_array=array();
$menuu_array["menuu"]="Menüü";
$menuu_array["keel"]=$keel;
$menuu_array["menuu_01"]="Algus";
$menuu_array["menuu_02"]="Projektid";
$menuu_array["menuu_03"]="Progemine";
$menuu_array["menuu_04"]="HTML";
$menuu_array["menuu_05"]="Mp3";
$menuu_array["menuu_06"]="Doom";
$menuu_array["menuu_07"]="Lingid";
$menuu_array["menuu_08"]="Tõmbamine";
$menuu_array["menuu_09"]="Serialz";
$menuu_array["menuu_10"]="Külalised";
$menuu_array["menuu_11"]="Kontakt";
$menuu_array["menuu_12"]="Filmid";
$menuu_array["menuu_13"]="Mängud";
$menuu_array["menuu_14"]="Programmid";
$menuu_array["menuu_15"]="Special";
?>