<table cellpadding="5" border="0">
<img src="graphics/rqmail.gif" hspace="5">
<tr><td class="text">
Rqmail on lihtne POP3/SMTP programm mailide lugemiseks ja saatmiseks.
Kasutasin seda oma vanal arvutil Outlooki asemel. Iga 30 sek järel konrollib kas on saabunud uus mail. Kahjuks on programm veel lõpetamata.
Nii et kui keegi soovib seda edasi arendada, siis lähtekood on ka saadaval. Kompileeritud Rapidq-ga.
<br><br>
Pop3 serveriks on solo.delfi.ee ( port 110 )
Smtp mail.neti.ee ( port 25 )
</td></tr>
<tr><td class="text">
<b>Tõmbamine:</b><br><br>
<li><a href="rqmail/rqmail_bin.zip" class="text">rqmail_bin.zip</a> - Rqmail programm.</li>
<li><a href="rqmail/rqmail_src.zip" class="text">rqmail_src.zip</a> - lähtekood.</li>
</td></tr>
</table>