<CENTER><FONT size="4"><B>Teretulemast minu kodulehele!</B></FONT></CENTER><BR><BR>
<TABLE align="center">
<TR><TD>[11:12] <A href="statistika.php" target="new">Statistika test</A></TD></TR>
<TR><TD>[30.11] <A href="doom.php" target="">Listatud Zdaemon 1.02 download</A></TD></TR>
<TR><TD>[27.11] <A href="playlist.txt" target="new">Special for dj_kaarel</A>
<TR><TD>[31.10] <A href="jutukas.php" target="">Jututuba avatud</A></TD></TR>
<TR><TD>[26.10] <A href="doom.php" target="">Võrgu doom(doom.zip) üleval</A></TD></TR>
<TR><TD>[26.10] Downloadidesse lisatud mitu programmi</TD></TR>
<TR><TD>[24.10] Mp3 nimekiri uuendatud ~550 lugu</TD></TR>
<TR><TD>[20.10] Lehekülg üleval</TD></TR>
</TABLE>

