<FONT size="4">Lingid :</FONT><BR>
<Li><A href="http://doom.getsomewhere.net" target="new">[doom.getsomewhere.net] - mitmesugused doomi failid</A></Li><BR><BR>
<Li><A href="http://www.zdaemon.com" target="">[Zdaemon'i ametlik weebileht]</A><BR><BR></Li>
<FONT size="4">Download :</FONT><BR>
<Li><A href="zdaemon102_bin.zip" target="">[Zdaemon 1.02]</A> - uus zdaemon!</Li><BR><BR>
<Li><A href="http://www.hot.ee/cljim/doom.zip" target="">[Doom.zip] - vajalik võrgus doomi mängimiseks</A></Li><BR><BR>
<FONT size="4">.wad failid :</FONT><BR>
<Li><A href="doommall.zip" target="">[Doommall.wad]</A> - </Li><A href="Doommall.txt" target="new">[Doommall.txt]</A>
