<applet code="ConferenceRoom.class" name=cr_applet codebase="http://clan.jutukas.ee/aplet" align="baseline" width="483" height="300">
                <param name="archive" value="http://clan.jutukas.ee/aplet/cr.zip">
                <param name="bg" value="cccccc">
                <param name="buttons" value="true">
                <param name="channel" value="#jim">
                <param name="colorpanel" value="false">
                <param name="fg" value="000000">
                <param name="guicolors" value="tickercolor=;tickertextcolor=000000;opercolor=ff0000;voicecolor=000000">
                <param name="guicolors1" value="sessioncolor=cccccc;sessiontextcolor=000000">
                <param name="guicolors2" value="titlecolor=808000;titletextcolor=000000">
                <param name="guicolors3"  value="noticeColor=990000;systemColor=0000ff">
                <param name="guicolors4" value="kickColor=ff0000;joincolor=0000ff;quitcolor=0000ff">
                <param name="nick" value="">
                <param name="nickprompt" value="H&uuml;&uuml;dnimi">
                <param name="passPrompt" value="Parool">
                <param name=size value="12">
                <param name="user" value="Koobas">
                <param name=font value="fixedsys">
                <param name="namePrompt" value="Sinu E-maili aadress">
                <param name="port" value="6667">
                <param name="roomPrompt" value="Jututoa nimi">
                <param name="roomsWidth" value="0">
                <param name="simple" value="Ruum">
                <param name="userWidth" value="21">
              </applet>
