<FONT size="5">Jimmy Cool :</FONT><BR><BR>
<TABLE border="0">
<TR><TD><Li>Nimi</Li></TD><TD>Jimmy Cool</TD></TR>
<TR><TD><Li>E-mail</Li></TD><TD><A href="mailto:cljim17@yahoo.com" target="">cljim17@yahoo.com</A></TD></TR>
<TR><TD><Li>Elukoht</Li></TD><TD>Elva</TD></TR>
<TR><TD><Li>Vanus</Li></TD><TD>17</TD></TR>
<TR><TD><Li>Telefon</Li></TD><TD>055962947</TD></TR>
<TR><TD><Li>Kool</Li></TD><TD>NRG</TD></TR>
</TABLE>
