<TABLE width="70%" height="1" border="1" bordercolor="#000000" cellspacing="0">
<TR>
        <TD>Ikoon</TD>
        <TD>Nimi</TD>
        <TD>Kirjeldus</TD>
        <TD>Suurus</TD>
</TR>
<TR>
        <TD><IMG src="adawaret.gif"></TD>
        <TD><A href="aaw.exe" target="">Ad-Aware 5.83</A></TD>
        <TD>Programm arvutist spyware eemaldamiseks</TD>
        <TD>871KB</TD>
</TR>
<TR>
       <TD><IMG src="winmx.gif"></TD>
       <TD><A href="winmx330.exe" target="">WinMx 3.30</A></TD>
       <TD>Parim failide jagamise programm</TD>
       <TD>748KB</TD>
</TR>
<TR>
       <TD><IMG src="xara.gif"></TD>
       <TD><A href="xara3d4.0+crack.exe" target="">Xara 3D 4.0 + Crack</A></TD>
       <TD>3D graafika tegemine</TD>
       <TD>~1MB</TD>
</TR>
<TR>
       <TD></TD>
       <TD><A href="DirectCd.rar" target="">DirectCd</A></TD>
       <TD></TD>
       <TD>~8MB</TD>
</TR>
<TR>
       <TD><IMG src="msn.gif"></TD>
       <TD><A href="Setup9x.exe" target="">MSN messenger (win 9x)</A></TD>
       <TD>Microsoft messenger</TD>
       <TD>3.9MB</TD>
</TR>
<TR>
       <TD><IMG src="unfreeze.gif"></TD>
       <TD><A href="UnFREEz.exe" target="">Unfreez</A></TD>
       <TD>Programm liikuvate gif'ide tegemiseks</TD>
       <TD>~30KB</TD>
</TR>
<TR>
        <TD><IMG src="msgif.gif"></TD>
        <TD><A href="gifsetup.exe" target="">GifAnimator</A></TD>
        <TD>Veel üks programm liikuvate gif'ide tegemiseks<BR>Microsoft Gif Animator</TD>
        <TD>1.05MB</TD>
</TR>
<TR>
        <TD><IMG src="transparentgif.gif"></TD>
        <TD><A href="TransparentGIF.exe" target="">TransparentGIF</A></TD>
        <TD>Teeb läbipaistvaid gif graafikat</TD>
        <TD>330KB</TD>
</TR>
</TABLE>
