doc:
	rm -rf srcdoc
	mkdir srcdoc
	docsrc arvuti.pl 'Põhiprogramm'
	docsrc otsing.pl 'Otsingustrateegiad'
	docsrc priority_queue.pl 'Prioriteetidega järjend'
	docsrc binary_tree.pl 'Kahendpuu'
	docsrc_index srcdoc
clean:
	rm -rf *~
	rm -rf *.dat
