clean:
	rm -rf *~
doc:
	rm -rf srcdoc
	mkdir srcdoc
	docsrc server.pl 'Othello server'
	docsrc othello.pl 'Mängu TI'
	docsrc html.pl 'Väljundi genereerimine'
	docsrc laud.pl 'Laua protseduurid'
	docsrc alfabeta.pl 'Alfa-beta otsing'
	docsrc_index srcdoc