Cabinet Manager 98 - Name - Finn Mac CooL - Cert - 1097 - Key - 2RE561163255 <br>
Cabinet Shell v1.04 - Name - Finn Mac CooL - Serial - 32624 <br>
Cache bomber 98 - Serial - tj100753 <br>
Cache Compacter v4.14 - Name - Finn Mac CooL - Serial - 78920S-1727614 <br>
Cache Watcher v1.10 - Serial - 1436 or 1384 or 1475 <br>
CAD-Draw v4.25 - Name - Finn Mac CooL - Serial - 04319-04.98-54309-294 <br>
Cakewalk v7.x - Serial - cwpa700000000 <br>
Cakewalk v8.0 - Serial - cwpa800000000 - CDKey - 769-800036-1541 <br>
Calendar Builder v3.1c - Name - Finn Mac CooL - Serial - RKS-1615562 <br>
Calender v2.2 - Name - Finn Mac CooL - Serial - mgui_21L: <br>
CalendEzy v1.02 - Serial - shgdf84627 <br>
Call Attendant v1.5 - Serial - 0410i0fvvk0g2080u420 <br>
Call-By-Call v2.4 (German) - Name - Sonixx - Serial - 6083-3983-7716-4890 <br>
Caller-ID Pro v1.4 - Serial - 19432 <br>
Caller-ID Pro v1.7 - Name - g-rom - Serial - 40250 <br>
CallTrak32 v3.02g - Name - Licensed User - Serial - 6139 9903 9181 5591 <br>
CallWatch v1.0 (Single) - Serial - V1DEMBK <br>
Calypso E-mail v2.40.41.08 - Serial - 3MBJ-8B4Y-GHFN-9X4G-89J7 <br>
Calypso Mail v2.40.39 - Serial - 3C7RPAXV69WFYLZPHHX2V <br>
Calypso Mail Lite v2.40b41 - Serial - 3Z779C6B93WMFPJGD6V5 or 3C7RPAX69WFYLZPHHX2V <br>
Calypso Mail Standard v2.40b41 - Serial - 37589TEXFPFP3BTM3MGSMW <br>
CAMCAD v3.0 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 589A6971 <br>
Canvas v6.0 Pro - Serial - X12Z-EXTOX908 <br>
Caos Graph 32 v2.0 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 25352-34622 <br>
Capture Professional v3.17b - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - C6-C1E-MEX-BJ6-7X <br>
Capture Professional v3.21f - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - C6-C1E-MEX-BJ6-7X <br>
Capture Professional v4.04 - Name - (Your name here) - Company - #CRACKS - Serial - DQVD-QRQLQ-QZ-Y44YL (5 Users) <br>
Capture Professional v4.04 - Name - (Your name here) - Company - #CRACKS - Serial - DQVX-Q4Q6Q-QA-NT4CL (Organizational) <br>
Carbon Copy 32 v5.00.222 - Name - (Your name here) - Company - (Your company here) - Serial - 4172451273912475 - Unlock Code - 2454861263164886 <br>
CardBase v2.9 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 3532782402 <br>
Carnet v1.4 - Serial - A6b45zxs <br>
CaseLinr v5.93 - Name - Finn Mac CooL - Serial - w8MWebtEXB <br>
Catz II (Retail) v1.00.01g4 - Serial - 206788199823 <br>
Catz II The Windows Screensaver - Serial - 3122-8598-8827 or 3119-2078-8789 or 3115-6978-7745 <br>
CCS Mini Phone Book v4.98.300 - Name - Phrozen Crew - Serial - 17440278 <br>
CD Box Labeler 98 v3.11 - Name - Registered User - Serial - 144868 <br>
CD Box Labeler 98 v3.14 - Name - #CRACKS - Serial - 63360 <br>
CD Box Labeler 98 v3.14 - Name - Finn Mac CooL - Serial - 118062 <br>
CD Box Labeler 98 v3.14 - Name - Registered User - Serial - 144868 <br>
CD Box Labeler 98 v3.17 - Name - Finn Mac CooL - Serial - 118062 <br>
CD Menu-Generator v2.27 - Name - Dana Stone - Serial - 954993300 <br>
CD Right Plus v1.1.251 - Serial - ABCD1F-123456 <br>
CD Spectrum Pro v3.4.345 - Serial - 51095 or 63827 or 64222 or 11181 or 702240 <br>
CD Streamer v3.01d - Serial - S/SANELLI/FIST+MASTER.LUCIAN.NET/EED17E67 <br>
CD VALET v3.31 - Name - (Your name here) - Serial - AbcDE-ABCDE-ABCDE-ABCDE or BAAAA-AAAAA-AAAAA-AAAAA <br>
CD Wizard v4.61 - Name - Finn M CooL - ID - 503 <br>
CD-Quick Cache v3.01 - Name - Finn_Mac_CooL - Serial - 349F <br>
CD-Quick Cache v3.01 - Name - FMC - Serial - 19A3 <br>
CD-Quick Cache v3.01 - Name - PC98 - Serial - D070 <br>
CD-Quick Cache v3.1 - Name - PC99 - Serial - D473 <br>
CD-R Diagnostic v1.16 - Name - Finn Mac CooL - Serial - ARAA14261 <br>
CD-R Diagnostic v1.25 - Name - #CRACKS - Serial - ARAA6162 <br>
CD-R Diagnostic v1.25 - Name - Finn Mac CooL - Serial - ARAA14261 <br>
CD-R Diagnostic v1.31 - Name - Finn Mac CooL - Serial - ARAA14261 <br>
CDEdit v1.02 - Name - Finn Mac CooL - Serial - 1685521927397 <br>
CDH Media Wizard v3.15 - Name - Finn Mac CooL - Serial - 5A86AC6FDAGD9EA <br>
cdrLabel v4.1 - Name - Finn Mac CooL - Serial #1 - 3896857095 - Serial #2 - 852058377 <br>
cdrLabel v4.1 - Name - (Your name here) - Serial #1 - 3896857095 - Serial #2 - 852058377 <br>
cdrLabel v4.1 - Name - FMC - Serial #1 - 35786759 - Serial #2 - 539100687 <br>
CDRWIN v3.5c - Name - Finn Mac CooL - Company - Fee Free Warez - Unlock - BF31F7ED-AD28FACF-F4FBF4A8-F037223A - Check - 4F06D5D7-12190D22-59D30E67-04CCD692 (don't use on 3.6a or u will have to reinstall) <br>
CDRWIN v3.6a - Name - Finn Mac CooL - Company - Fee Free Warez - Unlock - BF3106DC-AD28FACF-4BECF497-F037223A - Check - 4F0624E6-1219FC13-E6C40E58-BBDBD6AD (Beta) <br>
CDRWIN v3.6a - Name - Finn Mac CooL - Company - Fee Free Warez - Unlock - BF3181B9-AD28FACF-4BECF497-F037223A - Check - 4F06A383-12197B76-E6C40E58-BBDBD6AD (Final) <br>
CDRWIN v3.6a - Name - Finn Mac CooL - Company - #CRACKS - Unlock - FF10B1E5-3CDC16AE-D8B9529C-563CAA5A - Check - A92C1BBF-C3CCA74B-E4654432-8E85F8C6 (Final) <br>
CDRWIN v3.6a - Name - Finn Mac CooL - Company - #CRACKS - Unlock - FF103680-3CDC16AE-D8B9529C-563CAA5A - Check - A92C9CDA-C3CC202E-E4654432-8E85F8C6 (Final) <br>
CDWorx v2.x - Name - Finn Mac CooL - Reg - #CRACKS#CRACKS98 - Password - WAUFJUUKOAJXZHGG <br>
CGI*StarPro v3.5 - Serial - CP0000-US173-JK1N1-00000-3207634 <br>
ChatSpace IRC Server v1.4 - Serial - 8A33557902E2034416ECF2EA686D2DB5 or 6D4DC8CCE706D57DBEFB4189C66B2AF0 <br>
ChatSpace IRC Server v1.5 - Serial - 8A33557902E2034416ECF2EA686D2DB5 or 6D4DC8CCE706D57DBEFB4189C66B2AF0 <br>
Cheap Date v4.0d - Serial - 9876543eww00298 <br>
Check Files v1.5a - Name - Finn Mac CooL - Serial - 203287849 <br>
Check Point FireWall-1 v3.0 - Host - Any you like - Features - All - Key - FFFFDEAD-F91BA051-2DFC52CB <br>
CheckIt 98 v6.0 - Name - (Your name here) - Company - (Your company here) - Serial - DQ-405039 <br>
Checkit Network Optimizer v1.1 - Serial - MH-121630 or MH-119640 <br>
Check Sum Calculator v2.8 - Name - Finn Mac CooL - Serial - 680-686 <br>
CheckMail32 v1.65 - Name - Fully Licensed User - Serial - 172854391 <br>
CheckMail32 v1.70 - Name - <br>
Chem3D Studio v3.5 - Serial - 6506001 - Registration - ZWJCBIQSB <br>
Chem3D Studio v4.0 - Serial - 6506001 - Registration - ZWJCBIQSB <br>
Chord Pro Manager v1.0 - Name - TEX98 - Serial - 10003851 <br>
Chord Pro Manager v2.0 - Name - TEX98 - Serial - 64495430 <br>
Chord Pro Manager v3.01 - Name - TEX98 - Serial - 87564436 <br>
Christmas Music Player v4.0 - Serial - CMP843 <br>
Chromatica v1.2 - Serial - CCB-100-0001-000301256458 or CCB-123-1234-123456-330658 <br>
CineMac v1.3 - Serial - CFD101C3222 <br>
CircuitMaker v6.1a - Serial - 174142857 (Pro) <br>
CircuitMaker v6.1a - Serial - 131170439 (Student) <br>
Classify 98 v1.02.008 - Name - #CRACKS - Serial - CW-115420 <br>
Classify 98 v1.02.008 - Name - Finn Mac CooL - Serial - CW-337021 <br>
Clean Sweep Extra Strength v4.0 - Serial - CEWU400R071961 <br>
Cleansweep v4.0 Deluxe - Serial - CSWU400R071961 <br>
Cli-Mate v1.0 - Name - Finn Mac CooL - Serial - F14267L <br>
Cli-Mate v1.2 - Name - Finn Mac CooL - Serial - F14267L <br>
Click & Paste v3.0.2 - Serial - t03117g51-0301 <br>
Click & Paste v4.0 - Serial - cpt2845640 <br>
ClickBook v2.2.1 - Serial - CBWR-GY4CDU-HEX4H-NNR-7B8CP2 <br>
Clicker TX v1.01 - Name - The Master DaVinci - Serial - 0028874095 <br>
ClipCache v2.0 - Serial - 30050a0f-04090e03 <br>
ClipCache v2.12 - Serial - 30050a0f-04090e03 <br>
Clipmate v4.52 - Name - Finn Mac CooL - Serial - C6410512668 <br>
ClipMate 5.04 - Name - Einride [PC] - Serial - G019366204068 <br>
ClipQuik v1.02 - Name - TEX98 - Serial - 105-849-910-366 <br>
ClipQuik v1.03 - Name - Finn Mac CooL - Serial - 978-597-109-717 <br>
CloneMaster v2.19 - Name - tKC/PC '98 - Serial - 4FC59UEV93J4 <br>
CloneMaster v2.19 - Name - Underworld^SNT - Serial - 678358010 <br>
Close Popup v4.0 - Name - Finn Mac CooL - Serial - 1655;^cc`BVX`8ddA <br>
Cold Fusion Server v3.11 - Serial - CF31PWE-2278461021 or CF31PWE-4478461298 <br>
Cold Fusion Studio v3.11 - Serial - CF31SWE-9185240490 <br>
ColdFusion Server Enterprise v4.0 - Serial - CF40ENT-5127989016 <br>
ColdFusion Server Professional v4.0 - Serial - CF40PNT-5161343951 <br>
Color Converter v2.0b - Serial - KAC4250EWW10398 <br>
COM Explorer v1.0 - Name - Finn Mac CooL - Serial - 6769-X7CWPAF4 <br>
COM Explorer v1.5 - Name - Finn Mac CooL - Serial - 6769-X7CWPAF4 <br>
Com v6.9.9.62 - Name - Finn Mac CooL - Serial - 1595212135185 <br>
CompuPic v4.0 b955 - Serial - BBBH3QZX5VSBB <br>
CompuPic v4.0 b955 - Name - Finn Mac CooL - Phone - 976-PIMP - Serial - BH2KE6AARS <br>
Conference Room v1.5 - Name - CDWarez - Company - CDWarez - Serial - F5EA-23E8-49D2-E689 <br>
Conference Room v1.5.9d - Name - <br>
Conference Room v1.6.0 - Name - CDWarez - Company - VQi - Serial - F5EA-23E8-49D2-E689 <br>
Conference Room v1.6.1 - Name - aerosmith - Company - Ecg - Serial - 1A5F-356E-860F-08DB <br>
Conference Room v1.6.1a - Name - <br>
Conference Room v1.62 - Serial - E90B-32F5-E6F4-B30F <br>
Connect 2.0 - Serial - CNTC1949 <br>
ConnectPal Pro v5.0 - Name - Finn Mac CooL - Serial - #CRACKS1998 - Registration - 7WfUW_gEMML - CheckSum - FLJLLHDHHEDJJ <br>
ConnectPal Pro v6.0 - Name - VERSUS - Serial - 35776477-DHSJKE39876-3783998345678-4679467-LPDJEW-359 <br>
ConnectPal Pro v6.03 - Name - Finn Mac CooL - Serial - Z}##4auw4W$$` <br>
Cookie Crusher v2.0 - Serial - 14613 <br>
Cookie Crusher v2.0 - Name - The Keyboard Caper - Serial - 188809803 <br>
Cookie Pal v1.2b - Name - Finn Mac CooL - Serial - 2283308 <br>
Cookie Terminator v1.0 - Name - Finn Mac CooL - Serial - 6784-7UibSX9 <br>
Cookie Terminator v1.1 - Name - Finn Mac CooL - Serial - 6784-7UibSX9 <br>
Cool Page v1.3 - Serial - 3848316851 <br>
CoolCat v4.01 - Name - Finn Mac CooL - Serial#1 - 123456789 - Serial#2 - 7CE5-A58C-77CD <br>
CoolCat v4.02 - Name - Finn Mac CooL - Serial#1 - 123456789 - Serial#2 - 7CE5-A58C-77CD <br>
CoolZip v1.0 - Name - Finn Mac CooL - Serial - 58FD0819EB76A86FABA8849C60D6 <br>
CoolEdit 96 - Name - Finn Mac CooL - Serial - FMFBVECO <br>
CoolEdit 96 - Name - tHATDUDE PC96 - Serial - HFCMGACK <br>
CoolTaskBar v2.0 - name - stalker - Serial - 5701385 <br>
CoolTimer v1.2 - Serial - BennyElias <br>
Copernic 98 Plus v2.5 Serial - 999-111111114 or 564-056783023 or 999-700000000 or 708-174045482 or 032-842118122 or 373-404000000 or 373-220201194 or 581-771941286 or 815-491022388 <br>
Copernic 98 Plus v2.51 - Serial - 431-919475562 or 457-677345110 or 307-827697341 (Win98 only) <br>
Copernic 98 Plus v2.51 - Serial - 781-560255094 or 615-610780745 (All) <br>
COPSTalk v2.5 - Serial - OJVK21001817 <br>
CopyTo v2.1 - Name - Fully Licensed User - Serial - 1E612A4D148D381018774F7457207472 <br>
Correcteur 101 v3.0 - Serial - t9r u8x h6w r7s <br>
Corel Draw v8.0 - Serial - DR8XR-83G91247 or DR8XR-0074G719 or DR8XR-Q2636556 or DR8XR-79C34890 or DR8XR-8L66794825 or DR8XR-A7505549 <br>
Corel Suite v8.0 - Serial - WP8XR-91804200 <br>
Corel Ventura v8.0 - Serial - CV8-12345678 <br>
Corel WordPerfect v8.0 - Serial - WP8XR-91804200 <br>
Cosmo Code v2.5 - Serial - PFX0100B-ETC-1234-5678 <br>
Cosmo PageFx v1.0 - Serial - AZA0100C-DRA-8708-3284 <br>
Cosmo Worlds v2.0 - Serial - LXT3351C-SWP-2342-4612 or PFX0100B-ETC-1234-5678 <br>
Cover Your Tracks v3.0 - Name - Finn Mac CooL - Serial - twhv3ggk <br>
Cover Your Tracks v3.11 - Name - Finn Mac CooL - Serial - twhv93ggk <br>
CPUKiller v2.0 - Name - frenzy [C4A] - Serial - KJMAFKTTAIVSMFAI <br>
Create & Share Camera Pack - Serial - 0211CUSB01978 <br>
CreateInstall v3.13 - Name - CORE/DrRhui - Serial - F88D00F0 <br>
Cross Reader v1.09 - Serial - DEMOSTOPNOW <br>
Crossword Companion v4.1 - Name - (Your name here) - Serial - 5022-5025 <br>
Crossword Construction Kit 98 v3.1 - Name - CORE/DrRhui - Serial - 3334 F10F4 489B1 <br>
CRT v2.2 - Name - tKC - Company - PC '98 - Serial - 01-11-002794 - Expiration - Never - Key - F21SF6LUT6SI2VJCDKDK4TPRN2JTDTID <br>
CRT v2.2- Name - Finn Mac CooL - Company - #CRACKS - Serial - 01-11-002794 - Expiration - Never - Key - IF57K9OFUM1BF2I8KIOOBU6J3J097TM5 <br>
CRT v2.2.3 - Name - - Company - PC98 - Serial - 01-07-111998 - Expire - Never - Key - 9636 6970 3910 8563 7861 <br>
CRT v2.3b3 - Name - - Company - PC98 - Serial - 01-07-111998 - Expire - Never - Key - 9636 6970 3910 8563 7861 <br>
CRT v2.3b3 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 01-28-019980 - Expire - Never - Key - 1238 9317 5042 9842 5929 <br>
CRT v2.3 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 01-28-019980 - Expire - Never - Key - 1238 9317 5042 9842 5929 <br>
CRT v2.3.1 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 01-28-019980 - Expire - Never - Key - 1238 9317 5042 9842 5929 <br>
Crypto v3.2 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 3493596139 <br>
Crypto v3.5 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 3413330758 <br>
CSE HTML Validator v3.0 - Name - fallen - Serial - 10915996 <br>
CSE HTML Validator v3.0 - Name - Owner - Serial - 78249171 <br>
CSE HTML Validator v3.03 - Name - Finn Mac CooL - Serial - 14100101 <br>
Cuneiform v3.1 - Name - Guess Who? - Company - Cracks 'R' Us - Serial - 130-8D73-0720-CE60-0F52-07AA - Code - 0073884681 <br>
Cuseeme v3.1 - SCBTM-JTAHM-PIBCN-TBEJM-ANGBJ or SCBTK-NPJGG-PKHEG-MJDCT-TECLM <br>
Cuseeme v3.11.16 - Serial - SCBPD-LGANG-ACDAC-TACHN-GKLEJ <br>
Cuseeme v3.12 - Serial - SCBPD-LGANG-ACDAC-TACHN-GKLEJ or SCBTM-JTAHM-PIBCN-TBEJM-ANGBJ <br>
Customizer 98 v1.1.40 - Name - Finn Mac CooL - Serial - 54DA19B010DE48A13132F5AFB12BBB9EDC4D1 <br>
Cutter Joiner v2.1 - Serial - 709258910501375 <br>
CyberCam v2.01.05 - Name - Finn Mac CooL - Serial - GANVHEOKGKMLTZQOHGT-QIZTX <br>
