Dana v1.0 - Serial - 0912-2349-A818 <br>
Dancing Baby Screensaver v3.3.2.0 - Name - ThE STaRDoGG CHaMPioN [PC] - Serial - pJ.tpq7yGKGxg <br>
DataArmour v1.210 - Name - Sonixx - Company - [AnThraX] - # of Lisenses - 1 - Serial - E6E1 FC58 65D7 8213 0AB7 1A04 7D48 9D5B <br>
DataWidgets v3.0 - Serial - 01A0002-7142722 <br>
DataWidgets 3.0 Upgrade - Serial - 0430-0201000-3753189 <br>
DAO v3.5c - Name - Finn Mac CooL - Company - Fee Free Warez - Unlock - FB992050-45A6B0D7-81772E5F-2AC0910B - Check - D159B15B-BE3F9087-C4D19E88-ABB7BF54 <br>
DAO v3.6a - Name - Finn Mac CooL - Company - Fee Free Warez - Unlock - FB995604-45A6B0D7-8FD52E60-2AC0910B - Check - D159C70F-BE3FE6D3-CA739EB7-A515BF6B <br>
DAO v3.6a - Name - Finn Mac CooL - Company - #CRACKS - Unlock - C878B3ED-1AB21714-CC7612DD-167DB7E9 - Check - DE050404-D2CAA4F9-D6C405C9-DA0BA534 <br>
DayToday v1.0 - Serial - SQD-2517409 <br>
dbMail v1.3 - Serial - 4040427362 <br>
DeBabelizer Pro v4.5.1 - Serial - nuqaj-2slkp2-r7wkd8 or 72854-532757-234223 <br>
Deletor v2.2 - Serial - 00000000-00004655 or 6989296297684992 <br>
Delphi v4.0 - Serial - 100-002-1491 - Key/CD-Key - 76x2-5fx0 <br>
Delphi v4.0 - Serial - 200-000-0323 - Key/CD-Key - 2EX2-5FX0 <br>
Delphi v4.0 Client/Server - Serial - 100-004-0814 - Key/CD-Key - 76x3-5fx0 <br>
Delphi Package Loader v1.00.01 - Serial - L109D3PKG498S151 (if this doesn't werk, tell me) <br>
DemoShield v5.42 - Serial - DDFFF8-0540-A9885001703 or 93257-18952-45361-1 <br>
DeskShow v1.4 - Name - (Your name here) - Serial - 131987 <br>
Desktop Forcast v1.2.2 - Serial - DF-3010 <br>
Desktop Genie v1.0 - Serial - SKE47323SJW3DWA <br>
Desktop Server 98 v1.0.0.34 - Serial - frenzy [C4A] - Unlock Key 1 - $EECDD3E7 - Unlock Key 2 - $84E4E021 <br>
Desktop Surveillance 98 v2.51b - Name - MANIFEST - Serial - ODS00473564902907RPH <br>
Desktop Surveillance 98 v2.51c - Serial - ODS120056009SCC1000EQS17000GX <br>
Desktop Themes v1.78 - Name - Finn Mac CooL - Serial - 2107358508 <br>
Desktop Themes v1.80 - Name - Finn Mac CooL - Serial - 2107358508 <br>
Desktop Themes v1.84 - Name - Finn Mac CooL - Serial - 2107358508 <br>
Desktop Forecast v1.21 - Serial - DF-3020 or DF-3013 <br>
Dev Partner Studio v6.0 - Serial - 4800-1234b3-73 <br>
Dial Up Magic v1.7 - Name - Krogar [DSi] - Serial - 1061522191 <br>
Dial-Up Magic v1.7 - Name - Nobody - Serial - 1041621899 <br>
Dialer 2000 1.31 - Serial - 07-121198-342 <br>
DiceDeluxe v2.0 - Name - Finn Mac CooL - Serial - 304411 <br>
Digital Atmosphere v2.1 - Serial - 489-163-187 - Key - 3-4231-59-56 <br>
Digitize - Serial - 123456789 - Code - 876543210 <br>
Dir List v2.04 - Name - Finn Mac CooL - Serial - 7340220160 <br>
Direct X Uninstaller v0.3 - Name - Phrozen Crew - Serial - B3BNN5BZ <br>
DirectFTP v1.0 - Name - Finn Mac CooL - Serial - 63216634 <br>
Directory Monitor v4.02 - Serial - 7228D2392D00 <br>
Directory Monitor v4.03 - Serial - 21B9FA5CBE00 <br>
Directory Printer v2.2 - Serial - 2618572 <br>
Directory Sorter v2.1 - Name - Finn Mac CooL - Serial - 405757191 (Run DirSort, press 'About' button to enter 'About' dialog. Press 's', 'm', 'f', and you will see the registration dialog box.) <br>
Disappear 98 3.0 - Name - Finn Mac CooL - Serial - 987654 <br>
Disk Cleanup v3.1 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 3862346860 <br>
Disk Cleanup v3.3 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 3782081479 <br>
Disk Cleanup v3.3 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 3862346860 <br>
Disk Copy v4.2 - Name - Finn Mac CooL - Serial - cTpA,1174 <br>
Disk Monitor v2.4 - Name - Finn Mac CooL - Serial - 78F-78D <br>
DiskBase v5.1 - Name - frenzy - Company - C4A - Address - C4A - Licenses - 1 - Serial - 97cf870b <br>
DiscJuggler v1.01.199 - Serial - CDJ-E7C8D0AC-FU <br>
DiscPlay v3.2 - Name - (Your name here) - Company - (Your company here) - Password - SPP-30-DP32A17 - Serial - DP3-SNEM <br>
Diversion's Slots v1.1 - Name - Finn Mac CooL - Serial - E7E4 <br>
Diz Nfo v1.22 - Name - Finn Mac CooL - Serial - 1380260160 <br>
DLGplot v97.1.31 - Serial - 123456789 - Code - 876543210 <br>
DLL Show v3.6 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 3845602412 <br>
DLL Show v3.8 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 3845602412 <br>
DLL Show v3.8 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 3765337031 <br>
DNS Expert v1.3 - Serial - DXPW-fnhb-aw3q-2cgb-su83 <br>
-------------------------------------------------------------------------- <br>
DocFather Applet Edition v2.3 - Name - (Your name here) <br>
Serial - You can use any of the numbers between x - y <br>
X Y <br>
198346001 - 198346100 <br>
137621001 - 137621100 <br>
694233001 - 694233100 <br>
223448001 - 223448100 <br>
623289001 - 623289100 <br>
689877001 - 689877100 <br>
125127001 - 125127100 <br>
789065001 - 789065100 <br>
543273001 - 543273100 <br>
278924001 - 278924100 <br>
-------------------------------------------------------------------------- <br>
Dos Command Center v1.03b - Name - Finn Mac CooL - Serial - 481-538-246 <br>
DotHlp Pro v1.5 - Serial - 88776655 - Pass - 5B4D2574 <br>
DotHlp Pro v1.5 - Name - Lynda Rhiel - Serial - FOURSONS - Pass - 117F777A <br>
Download Assistant v1.3d - Serial - 1757196 or 1687236 or 4079624 or 1702782 or 1719525 or 1737607 or 1672761 or 1778489 or 1659251 or 1801717 or 1827157 or 2171578 <br>
Download Wizard Plus +v2.30 - Name - Finn Mac CooL - Serial - 3007-1967-3928-2420 <br>
Download Wizard Plus +v2.50 - Name - Finn Mac CooL - Serial - 3007-1967-3928-2420 <br>
Download Wonder v1.43 - Password - HELLO1 - Serial #1 - VMSX6XYKE7KMQEYDRSNPMNZ6H7UFZWF2 - Serial #2 - HQ5VR394ZZZZZZ9ZZZZZZZZZZ2E6MPKT <br>
DPEG v4.10 - Name - Finn Mac CooL - Serial - FMC18161919 <br>
DPEG v4.11 - Name - Finn Mac CooL - Serial - FMC18161919 <br>
DPS-Journal v2.0 - Name - Finn Mac CooL - Serial - 93685164676 <br>
DPS-Journal v3.0 - Name - Finn Mac CooL - Serial - 93685164676 <br>
Dr. Solomon's Antivirus Toolkit v7.59 - Serial - 1007226 <br>
Drag and File Gold v4.5b1 - Serial - CHEMINGCHEMINI <br>
DragAndScroll v2.0 - Name - stalker - Serial - 5701385 <br>
DragonScan - Password - puff <br>
DrawIt v2.0 - Serial - 081349 <br>
Drive Copy v2.0 - Serial - DC200ENCD-104568 <br>
Drive Explorer v7.0 - Finn Mac CooL - Serial - 9919-647442-96 <br>
Drive Image Pro v2.0 - Serial - DM200ENRCD-142067 or DM201ENRCD-193411 <br>
DropFolder v1.0 - Name - Finn Mac CooL - Serial - 121244476328 <br>
DropFolder v1.0 - Name - The Exterminators - Serial - 975051201452 <br>
Du meter v2.1 - Serial - DU2-PHROZENCREW-59612448 or DU2-FLU[X]/PC98-BCBA2995 or D2-000-00000000-9E30F022 <br>
DU Meter v2.11 - Name - frenzy - Serial - D2-Z9O-83367598-49C964B8 <br>
DUI Professional 98 v3.021 - Serial - 457283887941 <br>
Duplicate File Destroyer v2.5 - Serial - BFSDD - Activation Key - TCDFHCTB <br>
DV Book Manager v1.5 - Last Name - CREW - First Name - Phrozen - License Number - 12345 - Serial - 31463351 <br>
DVMPEG v4.32 - First Name - Like - Last Name - Weapon - Company - Topiland - Email - home@home.com - Serial - C3-0140-3861-EW7T <br>
DVMPEG v4.32 - First Name - Finn - Last Name - CooL - Company - #CRACKS - E-mail - cracks@cracks.com - Serial - 28-9YP6-9533-P794 <br>
DVMPEG v4.32 - First Name - Finn - Last Name - CooL - Company - #CRACKS - E-mail - cracks@cracks.com - Serial - 91-42E6-8X80-3769 <br>
DynaIP v2.1 - Name - Licensed User - Company - Licensed Company - Serial - 1556 <br>
