Hacker's View v5.91 - ftp://ftp.elf.stuba.sk/pub/pc/utilprog/hiew591.zip or ftp://ftp.cdrom.com/pub/sac/utilprog/hiew591.zip <br>
Hacker's View v6.01 - ftp://ftp.cdrom.com/.3/sac/utilprog/hiew601.zip <br>
HalfLife - Serial - 2437-63943-5344 (Multi Player) <br>
HalfLife - Serial - 8948-56098-9643 (Single Player) <br>
Halloween Slots - Serial - 606162 <br>
Hangman Delux v1.0 - Name - DaVinci & Spider] - Serial - 1.36388516841101E+60 <br>
HangMan v2.028 - Serial - 194-WKASR-0948 <br>
Hard Disk Sleeper v1.5 - Name - Finn Mac CooL - Serial - uupprmss <br>
Hard Drive Mechanic v3.0 - Serial - 65B10705 <br>
HardCopy v1.22 - Name - #CRACKS - Serial - YerHBQuRvn <br>
HardCopy v1.22 - Name - Finn Mac CooL - Serial - XlZLLVRMVv <br>
HardCopy v1.22 - Name - LawAbidingCriminalZ - Serial - XvClSpPsKZ <br>
HardCopy v1.4 - Name - #CRACKS - Serial - YerHBQuR0n <br>
HardCopy v1.4 - Name - Finn Mac CooL - Serial - XlZLLVRMV0 <br>
Hattrick Manager v0.34 - Name - Finn Mac CooL - Serial - 772223 <br>
Heart Smart v5.04 - Name - daze pC - Serial - 1956 <br>
Heart Smart v5.04 - Name - Registered Version - Serial - 5617 <br>
HEdit 32 v1.2 for NT - Name - Finn Mac CooL - Serial -3264 <br>
Helllp! - Name - Finn Mac CooL - Serial - 47609277 <br>
Hex-WorkShop v2.54 - Serial - SYTGAGIS or C4815UCF or 60666UCF or A9123ICE or MK121212 or SY-MDS95 or SYICEMAN or SY-lgb97 or SYREVOLT or SY000000 or 9Q-2EASY <br>
Hex Color Professional v1.0 - Serial - 0075-9590-3519-5652-0583-4163 <br>
HexWeb Typograph v2.0 - Name - Nop [Phrozen Crew] - Serial - BA3C6AF20E1F3A63 <br>
HighLighter v1.18 - Serial - HT10-0000928 <br>
HiJaak Pro v4.5 - Serial - 32750D73 <br>
Hippie 98 v3.0 - Name - SIG - Serial - 000000NXQ6X3X0B <br>
Hippie 98 v3.0 - Serial - #CRACKS - Code - CRACKS93FFNA207 <br>
Hippie 98 v3.0 - Serial - 12341234 - Code - 12312333A22F808 <br>
Hippie 98 v3.1 - Name - pCsK8R - Company - German Warez Alliance - ID - GWA - Code - GWA RULEZ <br>
HMView v2.21 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - DDCNDEIDUPKE <br>
HMView v2.31 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - DDCNDEIDUPKE <br>
HMView v2.31 - Name - Finn Mac CooL - Company - #CRACKS - Serial - ECBQEDAGCWNH <br>
Hockey Statistics Manager v1.47 - Serial - 802-199-911 (League License) <br>
Hockey Statistics Manager v1.47 - Serial - 802-199-912 (Team License) <br>
Holiday Lights v4.0.1 - Name - Phrozen Crew 98 - Serial - 977935219642 <br>
HomeSite v3.01 - Serial - HS30E-7827236639 or HS30E-RB2723PC98 or HS30E-7127230213 <br>
Homesite v4.0 - Serial - HS40E-727612 <br>
HoneyQ v1.2 - Serial - 23771-32447159 <br>
HoneyQ v1.21 - Serial - 23771-32447159 <br>
Horas v3.1 - Serial - 16193007-03040100 <br>
Hot Backgrounds v2.0 - Serial - 23077 or 24521 or 25495 or 29134 or 27796 or 43927 or 56144 or 46702 or 17455 or 51768 or 22576 or 48370 or 34453 or 13673 or 60376 or 19793 or 46829 <br>
Hot Buttons v2.0.0 - Serial 17455 <br>
Hot Chilli v2.5 - Name - Crystal - Serial - 1765-7654-8765 <br>
HotDog Express v1.52 - Identifier - ID-KAGF-F43G-2T66-UV78 - Registration Key - RK-7CC7-LH24-9E3W <br>
HotDog Express v1.52 - Identifier - ID-SHAN-JESS-CRAX-1998 - Registration Key - RK-NFBY-L6G6-1002 <br>
HotDog Professional v5.1 Webmaster Suite - Identifier - ID-EFIX-A111-B222-C333 - Key - RK-DQXZ-967G-8857 (be sure to register offline) <br>
HotDog Professional v5.1 Webmaster Suite - Identifier - ID-KAGF-F43G-2T66-UV78 - Key - RK-PCU7-23BK-TTHE (be sure to register offline) <br>
HotDog Professional v5.1 Webmaster Suite - Identifier - ID-SHAN-JESS-CRAX-1998 - Key - RK-ZKEP-623Q-3680 (be sure to register offline) <br>
Hotline Client v1.2 - Name - [k]rack Works - Serial - XKSVPSCATQOSMD <br>
Hotline Client v1.2 - Name - Finn Mac CooL - Serial - BNLDHKGZUPMNKD <br>
Hotline Client v1.2 - Name - HackUser - Serial - SHOUALIPZXMIYB <br>
Hotline Netscrawl v1.04 - Name - Finn Mac CooL - Serial - TOLWUBJGYHKMMD <br>
Hotline Server v1.2 - Name - [k]rack Works - Serial - FIWRMMKEDFHDOD <br>
Hotline Server v1.2 - Name - Finn Mac CooL - Serial - YKXIYBBDFEFYLD <br>
HoTMetaL Pro v5.0 - Serial - SQHC0 03A4C 877C5 <br>
Hotspot v1.0 - Name - Finn Mac CooL - Serial - s400,913,*113 <br>
HTML (Un)Compress v4.2 - Name - Hambo/CORE - Serial - sye05ZHw <br>
HTML Publisher Pro - Serial - M 143900 <br>
HTML Publisher Pro v2.10 - Serial - PUB 714430 <br>
HTMLed PRO v2.5 - Serial - P-3120-0002-1109 or P-2330-8154-4067 <br>
Hurricane 98 - Serial - 07-K08355 or 07-K08721 <br>
HYCD Publisher v4.8.1215 - Serial - RSUZVCDAAZB <br>
HYCD Publisher v4.9 - Serial - <br>
HyperCam v1.34 - Name - Bruiser - Key - JNAQ-MCOJ-HIAK-CUXC-DWCP-PAGD - Single User 1 copy <br>
HyperSnap-DX v3.21 - Name - Finn Mac CooL - Serial - BZQT-FGPE-LMXZ-XXXJ-BLGO-FQNN (Site) <br>
HyperSnap-DX v3.21 - Name - Finn Mac CooL - Serial - FTUB-FMOT-FQAL-JJJB-RNQM-XUHJ (World Wide) <br>
HyperSnap-DX v3.21 - Name - Zarkman [PC 98] - Serial - WUJL-ZPVE-KFRA-CRHZ-MLNB-DADI (World Wide) <br>
HyperSnap-DX v3.24 - Name - Finn Mac CooL - Serial - FTUB-FMOT-FQAL-JJJB-RNQM-XUHJ (World Wide) <br>
HyperSnap-DX v3.30 - Name - Finn Mac CooL - Serial - QKFP-WLDP-BOFV-WMON-FGJV-PNXF (World Wide) <br>
HyperSnap-DX v3.30 - Name - Finn Mac CooL - Serial - UNHU-SVBH-RKBD-ANRS-HQWK-BOCV (Site) <br>
HyperSnap-DX v3.30 - Name - Registered User - Serial - RQGZAYCTBIGMSYRWXVDIXOQN (Single) <br>
HyperSnap-DX v3.30 - Name - SWP '98 - Serial - ONKD-SCKN-ZOHA-RZWJ-FFEY-ETJR (World Wide) <br>
HyperSnap-DX v3.30 - Name - SWP '98 - Serial - UNHU-SVBT-RHXT-PIKX-RDQP-JMKF (Site) <br>
HyperText X/Press HTML Editor and X-Site project manager (PowerWeb) v1.2b - Name - Finn Mac CooL - Serial - PWR-2223669248-00 (you must register both for this to work) <br>
HyperVoxel v2.0 - ID - 1638 - Serial - Z124-P097-G586-A488 <br>
HWiNFO v4.44 - Name - Martin Malik - Serial - HW-5E39E4FF723B5B4360269F0000390B <br>
