K-Chess Elite v2.5 - Name - (Your name here) - Serial - KE700000 - Unlock Code - 7293 <br>
Kai Power Tools v3.02 - Serial - 07064-15906-01532 <br>
Kaleidoscope 95.1 - Name - Finn Mac CooL - Serial - ZUGUM <br>
Kaleidoscope 95.1 - Name - Registered User - Serial - DEMAZ <br>
Kalkulator/32 v2.16 - License Number - 0000 - Name - Finn Mac CooL - Serial#1 - 913455 - Serial#2 - 697958 <br>
Kawa v3.13 - Code - _RudeBoy_ - Serial - EAHC <br>
Keep It Safe v2.1 - Serial - 45198933 <br>
Kenny's Color Mixer v1.1 - Serial - mxyzptlk <br>
KeyText v1.17 - Name - Finn Mac CooL - Serial - 3355038D <br>
KeyView Pro v6.0 - Serial - 4000-0144-5297 <br>
KineMorphic Screensaver v2.1.640 - Serial - 65222 or 52095 or 11181 <br>
KineMorphic Screensaver v3.0.725 - Serial - 65222 or 52095 or 11181 <br>
KineMorphic Screensaver v3.1 - Serial - 65222 or 52095 or 11181 <br>
Klik & Play v1.0 - Serial - KPE10001143 or KPG10002097 or KPU10006512 or KPE10048950 <br>
Kremlin v2.21 - Serial - 4040053298 or 9398784011 or 9999632666 or 9876373079 <br>
