L0phtCrack v2.02 - Name - Finn Mac CooL - Serial - be1f1b1 <br>
l3enc v2.00 - Serial - 909GCB0A091E-9 <br>
l3enc v2.7 - Serial - 1000600200000B <br>
l3enc v2.72 - Serial - 1234107D90ABCC or F197BD39224291 <br>
LadyBird v1.2 - Serial - 1289Kermu! <br>
Lan Bridge v1.35.2 - Serial - 32088636460483 <br>
LanExpert v1.2 - Serial - 840-2580495 <br>
LanTastic v8.0 - Serial - 09950006389 - Key - 11112196EAE5 (33 users) <br>
LanTastic v8.0 - Serial - 09950006389 - Key - 111163854489 (99 users) <br>
LapLink Pro v8.0 - Serial - lprusun-139251-20a <br>
LAS Converter - Serial - LA123456789 - Code - 876543210 <br>
Laser Launcher v1.7 - First Name (Any name here) - Last Name - (Any name here) - Serial - 073068-060964 <br>
Launcher v2.0 - Name - Finn Mac CooL - Serial - 17B*,*97020 <br>
Leap Frog v2.1 - Serial - LPFR9865 <br>
LeapFTP v2.52 - Name - (Your name here) - Serial - PMN1-PM2N-P3MN-YZAX - Url - www.leapware.com <br>
Learn To Type v1.5 - Name - A - Code - 0 <br>
LingoMAIL v1.0 - Serial - 5300-0157-0469-1799 or 5241-8272-4052-3389 <br>
Link Sweeper v1.0 - Name - Finn Mac CooL - Serial - 1844362537 <br>
Link Sweeper v1.1a - Name - Finn Mac CooL - Serial - 1844362537 <br>
Link View internet Monitor v4.04 - Name - Freeware - Company - Freeware - Serial - 123-0,6-1.6 <br>
LinkBot Pro v3.6b - Serial - 1998 - Code - 580500 <br>
LinkFox v99.063 - Serial - F1*****0BD84CA5A5A418951 <br>
ListPro v1.1 - Name - Phrozen Crew 98 - Serial - 499701 <br>
LiquidFX Professional v4.0 R2 - Name - The Exterminators - Serial - AKNRTNOCJIPVRR <br>
LiquidFX v3.7 - Name - lxsc97 - Serial - IKNDBPINPMHPRL <br>
LiveImage v1.29a - Name - Finn Mac CooL - Serial - 52554145-20927-0572 <br>
LiveImage v1.29b - Name - Finn Mac CooL - Serial - 50004000-20007-0005 <br>
Lock v2.2 - Name - Finn Mac CooL - Serial - 503 <br>
Loki Diary v1.20.02 - Finn Mac CooL - Serial - 95C5740816 <br>
Log-a-Jog v2.4 - Code - V22272726 - Serial - 103339 <br>
Log-a-Jog v3.1 - Code - V22272726 - Serial - 103339 <br>
Logo Master v3.0 - Type perl2exe -register - Serial - ExEd! [Dsi],20527 <br>
LogPlot 98 - Serial - LP123456789 - Code - 55530 <br>
Lotus Notes v4.0 - Serial - 1F00028-01104360 <br>
LuraWave Studio v2.0 - Serial - LW2773-385313-256523 or LW2007-451221-431654 or WS1201-609894-654321 <br>
LView PRO v2.0 - Name - Finn Mac CooL - Serial - 1210-000-699934 <br>
LView PRO v2.1 - Name - Finn Mac CooL - Serial - 1210-000-699934 <br>
