Mac Drive 98 - Serial - MDC1-403WW-OWL010 <br>
Mac Opener v3.0 - Registration - 3844008-0104 - Key - A8A7-3A003QM7CMCQ <br>
Mac Opener v4.0 - Registration - 4201520-7457 - Key - 30MC-4000Q3M733MQ <br>
Macro Magic v3.4k - Serial - 54706993 or 99478965 or 32321007 or 14059824 <br>
Macro Magic v4.0d - Serial - 65727972 or 16224437 or 16079537 or 15944631 or 15818718 <br>
Macro Magic v4.0g - Serial - 65727972 or 16224437 or 16079537 or 15944631 or 15818718 <br>
Macro Magic v4.0j - Personal Edition - Serial - 15181354 <br>
Macro Magic v4.0j - Serial - 22136525 <br>
Macro Magic v4.1 - Serial - 22136525 or 14118392 or 36525107 or 17565579 or 18267783 <br>
Macromedia Director Shockwave Internet Studio v7.0 - Serial - DRW700-21771-30388-40404 <br>
Macromedia Director v6.0 - Serial - DRW600-09377-77068-20461 <br>
Macromedia Director v6.5 - Serial - DRW600-09377-77068-20461 <br>
Macromedia Director v7.0 - Serial - DRW700-21771-30388-40404 <br>
Macromedia DreamWeaver v1.2 - Serial - DWW100-01183-77026-89349 or DWW100-06086-07026-97518 or DWW100-07785-53546-55079 <br>
Macromedia DreamWeaver v2.0 - Serial - DWW200-05987-98274-58597 or DWW200-09785-18274-81630 <br>
Macromedia Dreamweaver v.3.0 - Serial - DWW300-08610-27280-95766,HS45EE-5030480010<br>
Macromedia Dreamweaver 3: DWW300-08610-27280-95766<br>
Macromedia Fireworks v1.0 - Serial - FWW100-25155-59778-11998 or FWW100-02052-07078-11451 <br>
Macromedia Fireworks v3.0 - Serial - FWW300-65137-37255-19336<br>
Macromedia Flash Generator - Serial - XFM100-03759-17013-19336 (Mac) <br>
Macromedia Flash Generator - Serial - XFW100-06858-07003-19336 or FLD200-03167-97071-57473 <br>
Macromedia Flash v3.0 - Serial - FLW300-13967-19732-16001 or FLW300-01567-53532-72983 <br>
Macromedia Freehand v8.0 - Serial - FHW800-08616-67028-30467 or FHW800-71323-77020-48487 <br>
Macromedia xRes v2.0 - Serial - 55020-0398-0128-22598 <br>
MagicMask v2.0 - Serial - CSB-200-0001-000216491264 <br>
MagicWin 98 v1.0 - Name - Finn Mac CooL - Serial - MGW192873 - Code - MGWJGMGPJ1110 <br>
MagnaRam 97 v3.0 - Serial - MRWU3000079159 <br>
Mail Control v4.0 (Build 9) - Name - Finn Mac CooL - Serial - ZX+ei <br>
MailGate v2.59 - Name - Finn Mac CooL - Serial - 175141535 <br>
Mailloop v4.0 - Serial - 3295631047 <br>
MailMax v2.02901 - Name - PREMiERE - Serial - X6A1SYQCZJD411 <br>
Main Actor v2.0 - Serial - 3294855 <br>
Major Submit v2.01 - Name - #CRACKS - Serial - 117946368 <br>
Major Submit v2.02 - Name - #CRACKS - Serial - 117946368 <br>
Make your own Screen Saver v3.4d - Serial - 21920129-QW49M9-123012903 - License - Leave Blank <br>
MapDraw v5.11 - Serial - 115885728049832487380598750 or 115887961567890123456789012 <br>
MapEdit v2.44 - Serial - LAMNBKBB <br>
Maple VR5 - Site Name - WMI - Campus Wide License - WIN-55NC-567980-7 - Users - 0 - System Type - IBM INTEL NT - HostID - (none) - Serial - C0658174E284561 <br>
Marathon Infinity - Full License Serial (Mac) - L2X4HEHLE7L7ZYHE <br>
Marathon Infinity - Net Only Serial (Mac) - 768GUYU7L7LPEUM <br>
Master Converter v2.05 - Serial - 211684*624032 or 314717*880414 <br>
MathCAD v8.0 - Serial - VN800809DH0697 (Standard) <br>
MathCAD v8.0 - Serial - PN807777DN7777 (Professional) <br>
Mathematica v3.0 - Serial - 4004026443-34646-361 <br>
Matlab v5.0 - Serial - 06492-09293-48567-50690-50674 <br>
Matlab v5.01 - Serial - 14976-02590-24715-61170-60415 <br>
Matlab v5.20 - Serial - <br>
Maximizer v5.0 - Serial - 01415101010699 <br>
Maze Escape v2.2 - Serial - MMZZ4488 <br>
McAfee - ftp.mcafee.com/licensed - login: licensed - pass: 321 <br>
McAfee VirusScan v3.20 - Serial - E000-PFMF-ZB9K <br>
MDaemon v2.5 - Serial - 100-01-03099-154-03694 (5 user license) <br>
MDaemon v2.5 - Serial - 100-02-01629-152-09335 (25 user license) <br>
MDaemon v2.5 - Serial - 100-03-06499-151-00074 (50 user license) <br>
MDaemon v2.5 - Serial - 100-04-05829-154-00493 (5000 user license) <br>
MDaemon v2.72 - Serial - 100-01-06584-153-03609 (5 user license) <br>
MDaemon v2.72 - Serial - 100-02-00438-152-04982 (25 user license) <br>
MDaemon v2.72 - Serial - 100-03-03901-141-01100 (50 user license) <br>
MDaemon v2.72 - Serial - 100-04-00996-155-02772 (5000 user license) <br>
MDaemon v2.74 - Serial - 100-01-06584-153-03609 (5 user license) <br>
MDaemon v2.74 - Serial - 100-02-00438-152-04982 (25 user license) <br>
MDaemon v2.74 - Serial - 100-03-03901-141-01100 (50 user license) <br>
MDaemon v2.74 - Serial - 100-04-00996-155-02772 (5000 user license) <br>
Measure v1.0 - Name - (Your name here) - Serial - 0000000X (where X is any number 1-9) <br>
Media Changer Deluxe v4.02 - Name - Finn Mac CooL - Serial - 6582 <br>
Media Changer Deluxe v4.03 - Name - Finn Mac CooL - Serial - 6582 <br>
MediaSauce v2.0 - Name - Finn Mac CooL - Serial - 140623 <br>
Melody v1.4 - Name - Finn Mac CooL - Serial - 141513 <br>
Mem Monitor v1.6 - Name - Phrozen Crew - Serial - 73574F <br>
MemoryAnalyst v1.01 - Name - Finn Mac CooL - Serial - MA3291 <br>
Mercur v3.0 - Serial - LORI-0000001-0000002 <br>
Message Parse v1.72 - Serial - 3860-6478-2718 <br>
Meta Master v1.2 - Serial - -34548 <br>
MetaFix v2.5 - Finn Mac CooL - Serial - 2F33D19B <br>
MetaInfo SendMail v2.5 - Serial - 1234/0b22.0b4f <br>
Metz v3.0 - Name - (Your name here) - Serial - MTZ 2 100 1001 <br>
Micropath 2001 v2.1319 - Serial - UCF-nnnnnoo <br>
Microsoft Access ADI - Serial - 040-0164120 or 040-1602212 <br>
Microsoft Generic OEM Serial - 09595-oem-09595-09595 and a generic CD key is 0401-6116000 <br>
MicroSoft Office 97 - cd key - 8068-2194354 or 4190-0298385 or 5545-3108110 or 3491-3108110 or 0201-11201D2 or 0701-0743365 or 4390-0057484 <br>
MicroSoft Office 97 - Serial - 53491-806-2194354-00000 or 34297-OEM-0028443-24567 <br>
Microsoft Office 2000 B2 - Serial - BBH2G-D2VK9-QD4M9-F63XB-43C33 or MP4F9-W6C8V-HTCCT-T7M7R-Y7K3Y or BKH8V-8G6XR-69WCQ-QDHVJ-4TFDY <br>
Microsoft Office 2000 B2 - Serial - 6E8DD200-AB04-11D1-B5B8-006097C998E7 <br>
Microsoft Office 2000 B3 - Serial - BBH2G-D2VK9-QD4M9-F63XB-43C33 or MP4F9-W6C8V-HTCCT-T7M7R-Y7K3Y or BKH8V-8G6XR-69WCQ-QDHVJ-4TFDY <br>
Microsoft Plus 98 - Serial - 1112-1104010 or 1111-1111111 or 813-9451002 <br>
Microsoft Project 98 - Serial - 1034-0647031 or 1034-1567002 <br>
Microsoft Project 98 - Upgrade Serial - 0402-3650815 <br>
MicroSoft Publisher 98 - Serial - 8112-3861226 or 8090-3186514 or 5890-8957776 <br>
MIDI Genie v1.90 - Name - Finn Mac CooL - Company - (Your company here) - Serial - 432031547 <br>
Midi-Switch v1.40 - Name - Serial - Finn Mac CooL - Serial - 811-682-111-010 <br>
Midpoint Companion v2.02 - Serial - 0800001116-48051 <br>
MightyFAX v2.8 - Name - Finn Mac CooL - Serial - RKS-5659753 <br>
MightyFAX v2.9b - Name - Finn Mac CooL - Serial - RKS-5659753 <br>
Mind Manager v3.5 - Serial - 6111-1115-1C11 <br>
Mine Field v1.025 - Serial - 741-NVMLA-8394 <br>
MiniCalc v1.0 - Name - Spider] - Serial - 1666805736 <br>
Minirun Package v1.0 - Name - Finn Mac CooL - Serial - 117595138848 <br>
mIRC v5.31 - Name - (Your name here) - Serial - 0-000 <br>
mIRC v5.41 - Name - #CRACKS - Serial - 3388-244885 <br>
mIRC v5.41 - Name - (Your name here) - Serial - 4321-86122 <br>
Mixman Studio - Serial - 2166362425 <br>
MixMan Studio Pro v1.6 - Serial - 2197871043 <br>
Mocha W32 Telnet/TN3270 - Name - Finn Mac CooL - Serial - A50960 (single) <br>
Mocha W32 Telnet/TN3270 - Name - Finn Mac CooL - Serial - B37952 (company) <br>
Mocha W32 TN5250 - Name - Finn Mac CooL - Serial - A44688 (single) <br>
Mocha W32 TN5250 - Name - Finn Mac CooL - Serial - B29248 (company) <br>
Mod4Win v2.30 - Name - Finn Mac CooL - Company - Fee Free Warez - Payment - Visa - Reg-Code - 366557730088308652 <br>
Modemshare 32 - Serial - 59980006304 - Key - 111111-CB36-C7 <br>
Modemshare 32 - Serial - 79980004675 - Key - 1CB203-A2CC-8E <br>
More Than Words v3.0 - Name - (Your name here) - Serial - X37-222-733-37x <br>
Monty's Mazes v2.2 - Serial - MMAZ6532 <br>
MoonPhase v2.1 - Serial - CBM-4051385 <br>
Moraff MoreJongg v7.0 - Serial - 0415-7797-4351 <br>
Morse Code Explorer v1.3 - Name - Finn Mac CooL - Serial - 67D-67F <br>
Motivator Pro v4.6b - Serial - 564864796-11210111581 <br>
.MP3 Producer v2.1 - Name - NATHON J. CARTER - Serial - AWVtHVkdtaeVAoasv6GdxAIGB <br>
MP3/Tag Studio v1.1 - Name - C4A Team - Serial - 701644aooc <br>
MP3/Tag Studio v1.1 - Name - zoin - Serial - 8631kwkdvj <br>
MP3/Tag Studio v1.2 - Name - mISTER fANATIC [C4A] - Serial - a286045i6q <br>
MP3 Explorer v1.10 - Name - TEX98 - Serial - 193980111-27855 <br>
MP3 to EXE v1.01 - Name - The Keyboard Caper - Serial - Crackers in Action - Reg Code - 44C7E9EE440C58E8 <br>
MP3 to EXE v1.02 - Name - cRACKiNG 4 aLL - Serial - C4A - Reg Code - 0207546D6BFDBB4E <br>
MP3 to EXE v1.5 - Name - PC98 - Serial - MP3-PC98 - Code - 03D489AA55C5FB09 <br>
mp3enc v3.0 - Name - Paul Gossett - Serial - ApFjn9CE8WVmYr/SzCBm/h/f3 <br>
mp3enc v3.1 - Name - Paul Gossett - Serial - ApFjn9CE8WVmYr/SzCBm/h/f3 <br>
MP3Wolf v1.04 - Name - Finn Mac CooL - Serial - MW-842173 <br>
Mr. Internet v3.5 - Name - Finn Mac CooL - Serial - 2941;^cc`BVX`8ddA <br>
MS Home Essentials - PID# - 34297-OEM-0028396-45801 <br>
Multi Clipboard v8.1203 - Serial - MC71542 <br>
Multi-App! v2.01 - Name - (Your name here) - Serial - ma1221 <br>
Multi-Edit v8.0 - Serial - MEW800e899283 or MEW800e894152 <br>
MultiDesk v2.50 - Name - Finn Mac CooL - Serial - B44D5D15 <br>
Multimedia Builder v1.2 - Name - #CRACKS - Serial - 276208-407 <br>
Multimedia Builder v1.2 - Name - Finn Mac CooL - Serial - 275585-414 <br>
Multimedia Builder v1.3 - Name - (Your name here) - Serial - 1-1001-288 <br>
Multimedia Builder v2.0 - Name - (Your name here) - Serial - 1-1001-288 <br>
Multimedia Builder v3.0 - Name - (Your name here) - Serial - 1-1001-288 <br>
Multimedia Builder v3.0 - Name - #CRACKS - Serial - 1-276208-407 <br>
Multimedia Builder v3.0 - Name - Finn Mac CooL - Serial - 1-275585-414 <br>
Multimedia Builder v3.1 - Name - Finn Mac CooL - Serial - 1-275585-414 <br>
MultiMedia Manager v2.0d - Name - Finn Mac CooL - Serial - 05546-111-946ET (Educational) <br>
MultiMedia Manager v2.0d - Name - Finn Mac CooL - Serial - 07302-111-777WZ (WorldWide) <br>
MultiMedia Manager v2.0d - Name - Finn Mac CooL - Serial - 07615-111-916SL (Single) <br>
MultiMedia Manager v2.0d - Name - Finn Mac CooL - Serial - 14689-111-213AF (Site) <br>
MultiMedia Manager v2.0d - Name - mpbaer - Serial - 00236-009-213AF (Site) <br>
MultiMedia Manager v2.0d - Name - mpbaer - Serial - 00236-009-916SL (Single) <br>
MultiMedia Manager v2.0d - Name - mpbaer - Serial - 00236-009-777WZ (WorldWide) <br>
MultiMedia Manager v2.0d - Name - mpbaer - Serial - 00236-009-946ET (Educational) <br>
Multimedia Xplorer v1.40b - Name - Finn Mac CooL - Serial - 995780355 <br>
Multimedia Xplorer v2.02 - Name - Finn Mac CooL - Serial - 995780355 <br>
Multimedia Xplorer v2.07 - Name - Finn Mac CooL - Serial - 10953835 (latest) <br>
Multiview 2000 v4.0 - Serial - 0w1g001751lalxsaikh <br>
Multiview 2000 v4.0 Server - Serial - 0w1g001751lalxsaikh <br>
Music Filer 98 Pro v1.0 - Serial - Ni05Ba04La4613666666 <br>
MyCat BMP to ICO v3.0.3 - Serial - 777T4657 <br>
