Namo Web Editor v2.03 - Name - Finn Mac CooL - Serial - 9597C81D71F583BE6AB575AE <br>
N-Track v2.218 - Name - Key - blues - Serial - yzarcma <br>
N-Track Studio v1.10 - Name - CORE/DrRhui - ID - ghf77862 - Serial - QHHKK-THGMCM <br>
NAT1000 v2.0 proxy - Serial - 1-900872550-889538355 <br>
NAT1000 v2.0 proxy for WinNT - Serial - 1-939028574-2018199347 <br>
NAT1000 v3.0 - Serial - <br>
NAT32 v5.0 - Name - Aurea Stoll - Code - 263607418 <br>
NAT32 v5.5 - Name - Finn Mac CooL - Code - 000000563 <br>
NAT32 v6.2 - Name - <br>
NAT32 v6.4.4 - Name - <br>
Nero Burning ROM v3.0.6.0 - Serial - 1302-9369-3051-3963 <br>
Nero Burning ROM v3.0.7.0 - Serial - 1404-1111-1329-6809 <br>
Nero Burning ROM v3.0.7.1 - Serial - 1404-1111-1329-6809 <br>
Nero Burning ROM v4.0.0.1 - Serial - 1441-0000-0020-2999-4055 <br>
Nero Burning ROM v4.0.0.2 - Serial - 1441-0000-0020-2999-4055 <br>
Nero Burning ROM v4.0.0.5 - Serial - 1413-0000-0031-2733-1673 or 1460-0000-0011-6483-2767 <br>
Nero Burning ROM v4.0.0.5 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 1521110133711493 <br>
Nero CD Creator v3.0 - Name - Finn Mac CooL - Serial - 3744819477241564 <br>
Net Submitter Pro v1.545 - Serial - AATKP63ADP59S8A <br>
Net Toob v3.5 - Serial - WKXBNRUEJ <br>
Net-It Now! v1.6 - Serial - COOL7034811840 <br>
NeTalk v1.02 - Serial - 100002-32562116 <br>
NetBoy v1.23 - Serial - NB11-01-11111111-rfyhamrarl or NB12-TR-14031998-idstchamlz <br>
NetBoy v1.31 - Serial - NB10-01-12345678-1234567890 <br>
Netbuster v1.31 - Serial - PF-940827-2030 <br>
NetContact v6.2 - Name -Gura Philip - Pin ID - 3387 <br>
Netobjects Fusion v3.0.1 - Serial - NFW-300-P-077-01851-47469 <br>
NetFolder v2.1 - Serial - LSR71-QZA29-MWK17-CHNS <br>
NetPal v1.1b - Name - CDWarez - Serial - 2349453 <br>
NetPop-Up v2.51 - Serial - 83267147Registered <br>
NetProxy v2.0.54 - Name - _RudeBoy_ / Phrozen Crew - Serial - JOTGMECIJWLN <br>
NetProxy v2.0.54 - Name - mISTER fANATIC [C4A] - Serial - HPYHSH9RJKHT <br>
NetProxy v3.03 - Name - The Exterminators - Serial - XSKQZ1LQXS (Unlimited) <br>
NetProxy v3.03 - Name - The Exterminators - Serial - XSKQZZWCQS (666 users) <br>
NetScape Cache Explorer v1.31 - Name - Plushmm [PC'98] - Serial - bbghhaja <br>
NetScape Cache Explorer v1.32 - Name - Finn Mac CooL - Serial - uupprmtq <br>
NetSwitcher v2.96 - Serial - 99999999999999999999999999994 <br>
NetTerm v4.2.8 - Name - Finn Mac CooL - Serial - 811c85k6 <br>
NetTerm v4.2.9 - <br>
NetToob v2.1 - Serial - WHD-POS-MWU-NET - Return Code - ENY-FZN-ROQ <br>
Network Clipboard v1.0 - Company - PC'98 - First and Last Names - Black Thorne - License - UNLIMITED - Serial - 83978676 <br>
NetZip v6.3045 - Serial - ww34566= <br>
News Grabber v2.118 - Name - DASavant [AnThraX] - Serial - 075410059106 <br>
News Grabber v2.118 - Name - Finn Mac CooL - Serial - 117058021460 <br>
News Poster Pro v5.34 - Finn Mac CooL - Company - #CRACKS - Serial - <br>
News Rover v3.3 - Name - Finn Mac CooL - Serial - 555673128 or 552522280 <br>
NewsBin v2.24 - Name - Finn Mac CooL - E-Mail - cracks@cracks.com - Serial - a23cec27-e5d313d2-4fd793ce <br>
NewsBin v2.26 - Name - Finn Mac CooL - E-Mail - cracks@cracks.com - Serial - A23CEC27-E5D313D2-4FD793CE <br>
NewsFerret v1.1102 - Serial - NS-100-002-267 - Key - F1B7-E584 <br>
NewsMonger v1.51 - Name - Finn Mac CooL - Serial - C311219731337098 <br>
Nic O Matic v1.71 - Serial - cn1-mfvfqb-3242y <br>
Nicos Commander v4.1 - Serial - 36TEZX0000 or AACDLUYXG or 36TZEX0000 <br>
NJWin v1.6 - Just place this reg info into your njwin.ini which is in C:\WINDOWS (Recommended bottom) <br>
[Registration] <br>
UserName=mISTER fANATIC <br>
CompanyName=cRACKiNG 4 aLL <br>
SerialNumber=???????????? <br>
Nomad News v1.43 - Serial - 256403685-956514841 <br>
Notebook v4.6 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 3283311560 <br>
Notebook v5.2 - Name - Finn Mac CooL - Serial - zki,,2,*83742 <br>
Noteworthy Composer v1.55a - Name - Me! - Serial - 345-014-101834 <br>
Notpad v2.61 - Name - TEX98 - Serial - 1472148050 <br>
Numega BoundsChecker for C++ Builder v6.01 - Serial - 6309-00009F-9F <br>
Numega BoundsChecker for Visual C++ v6.01 - Serial - 6109-00009B-9F <br>
NuMega CodeReview v6.1 - Serial - 6509-00009F-9F <br>
Numega FailSafe v5.21 - Serial - 4809-0000DB-9F <br>
Numega JCheck v1.20 - Serial - 4809-0000DB-9F <br>
Numega SmartCheck v6.0 - Name - #CRACKS - Serial - 1532-2342FF-DD <br>
Numega SmartCheck v6.0 - Name - Finn Mac CooL - Serial - 4004-3345BB-BB <br>
Numega SmartCheck v6.0 - Serial - 6405-091311-5B - url - http://216.49.10.245/ha/harvestr-webjump/smtchk60.zip <br>
Numega SmartCheck v6.01 - Serial - 6401-67343B-77 - url - <br>
Numega TrueTime for Visual Basic v1.20 - Serial - 2809-0000FB-9F <br>
Numega TrueTime for Visual C++ v1.20 - Serial - 2819-0000FB-DF <br>
Numega TrueTime for Visual Java v1.20 - Serial - 2829-0000FB-DF <br>
