RA2WAV v1.0 - Serial - 1010101 - Code - 1111A74 <br>
RA2WAV v1.5 - Serial - 19981998 - Code - 23A585W <br>
RAM / Swapfile Monitor v1.0 - Finn Mac CooL - Serial - 78F-795 <br>
Rand McNally Route Planner - Serial - RP9810CRM901-06693 <br>
Rascal Pro v1.6 - Serial - 16190025-19050000 <br>
RasMon v1.23 - Name - TEX98 - Serial - 516983895 <br>
RasTracker NT v2.0 - Company - #CRACKS - Number of Servers - 200 - Number of ports 900 - Serial- 819200 BBBCGFC 117234 <br>
Ray Dream Studio v5.0 - Serial - SW-500-1-4356-32162 <br>
RayFlect FourSeasons Plugin v1.0 - Serial - 4SP-W-01-xxxxxxx-xxxxxxx-xxxxxxx (x is any #) <br>
Reachout v7.0 - Serial - 1031-0255-8002-6515 <br>
Real Player Plus G2 v6.0.1.206 - Serial - 0301-83-4661 or 0244-27-2669 or 0016-40-9467 or 0016-78-4461 or 0186-95-9261 or 0097-62-7186 or 0256-04-4763 or 0094-32-4766 or 0600-64-2849 <br>
Real Player Plus G2 v6.0.2.196 - Serial - 0301-83-4661 or 0244-27-2669 or 0094-32-4766 or 0016-40-9467 or 0016-78-4461 or 0186-95-9261 or 0097-62-7186 or 0256-04-4763 or 0094-32-4766 or 0600-64-2849 <br>
Real Player Plus G2 v6.0.3.131 - Serial - 0301-83-4661 or 0244-27-2669 or 0094-32-4766 or 0016-40-9467 or 0016-78-4461 or 0186-95-9261 or 0097-62-7186 or 0256-04-4763 or 0094-32-4766 or 0600-64-2849 <br>
Real Producer Plus G2 - Serial - 212-08806-1648 <br>
Real Publisher G2 - Serial - 212-06851-6208 <br>
Real Server v5.0 - Name - Finn Mac CooL - Serial - 3b710a0a3780891ea83790d00160f70707e016fa8051288efa7021bf2ab7889083600 <br>
Realize Voice v2.11 - Serial - DR-RV20-00001437 <br>
Realize Voice Lite v2.11 - Serial - DR-RV20-00001400 <br>
Realize Voice v2.11 for ACT! - Serial - DRACT20-00001405 <br>
RecAll v2.3 - Name - Finn Mac CooL - Serial - F946D9F05 <br>
RecALL-PRO v1.0 - Name - <br>
RecipeBox v5.5 - Name - TEX98 - Serial - Error <br>
Record Catalog v1.0 - Serial - aax12axx21 <br>
RecoverNT v2.5 - Serial - RV55555-2705418 <br>
RecoverNT v3.0 - Serial - RV11402-4755667 <br>
RedHand v4.0a - Name - Mexelite - Serial - 163D1C1915150804 <br>
Reg Medic v2.0.02 - Serial - <br>
Reg Repair 2000 v2.2.03 - Serial - 911-31408 <br>
Reg Repair 2000 v2.4.04 - Serial - 911-31408 <br>
Reg Repair 2000 v3.3.02 - Serial - <br>
ReGet Pro v1.3.2 - Name - Finn Mac CooL - E-Mail - finn@cracks.com - Registration Code - NJUUGJ98HAYRAS98 <br>
Registry Bookmarks v1.0 - Name - Finn Mac CooL - Serial - 8266-pH55KMZ <br>
Registry Crawler v1.2 - Name - #CRACKS98 - Serial - 8267-$3BK$ <br>
Registry Run Guard v2.00 - Name - Black Thorne - PC'98 - Serial - 78765077317B50756261 <br>
Registry Search + Replace v2.10 - Name - Finn Mac CooL - User info - Fee Free Warez - Serial - 12F63309-xxxx - xxxx = any number <br>
RelayFax v2.4 - Serial - FAJYHHD-KJWATBO-RFYZNCI <br>
Reminder v4.52 - Name - Finn Mac CooL - Serial - A16-35M-3599 <br>
Reminder v4.53 - Name - Finn Mac CooL - Serial - A16-35M-3599 <br>
Reminder v4.53 - Name - #CRACKS - Serial - A16-35M-1748 <br>
Reminders v3.5 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 3821436871 <br>
Remote Control CD Player v4.013 - Serial - 247012546 <br>
Remote Control v1.5.51 - Name - Bisoux - Serial - 217152435F <br>
RenderSoft VRML Editor v1.7 - Serial - PRSEPLA1OIOZ or PRSODAT1BRKZ or PRSBQKW1SDRZ <br>
Replace it! v1.5a - Serial - 0047 <br>
Resize Image v2.3 - Name - Black Thorne - PC'98 - Code Key - C4D21375 <br>
Resize Image v3.3 - Name - Finn Mac CooL - Serial - A41213C5 <br>
RGB Editor v3.0 - Name - Freeware - Company - LawAbidingCriminalZ - Code - cc7de5a9 <br>
RGB Editor v3.3 - Name - Finn Mac CooL - Company - #CRAKCS - Serial - 3317124040 <br>
Rhino 3D Nurbs Modeler v1.0 - Serial - 1296-4271 <br>
RSConvert v2.0 - Serial - 1965-0002973 <br>
RSVP v1.12 - Serial - 4959382452 <br>
Rummy Drop v1.11 - Name - Registered User - Serial - 08o8ho008j910r <br>
RZSplit 97 v2.5 - Serial - 56911482 <br>
