SafeHouse v1.80.04 - Serial - us.checkpoint <br>
SafetyScan v2.5f - Serial - 7340680 or 7524180 or 7429153 or 18748435 <br>
SafetyScan v2.5i - Serial - 6462490 <br>
Sax Basic Engine Enterprise v5.01.05 - Serial - 2350-4177296-05 <br>
Sax Basic Engine Professional v5.01.05 - Serial - 2250-2389087-72 <br>
Sax Comm Objects Pro v3.099 - Serial - 1230-8595630-41 <br>
Sax mPower 98 Professional v3.02 - Serial - 5120-2339087-62 <br>
Sax Setup 98 - Serial - 3130-3091185-96 <br>
Sax Setup v98.01234 - Serial - 3130-4125296-00 <br>
Scitech Display Doctor v6.53 - Name - Finn Mac CooL - Serial - 18410-FF9AC5CF-80510 <br>
Scribe 95 v1.53 - Name - Finn Mac CooL - Serial - 5833919 <br>
Screen Loupe v4.1 / v1.7 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 3046010855 <br>
Screen Loupe v4.2 / v1.7 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 3046010855 <br>
Screen Loupe v4.3 / v1.7 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 2965745474 <br>
Screenario v1.1 - Serial - CD328377 <br>
Screen Saver Activate v1.5 - Name - Finn Mac CooL - Serial - 475 <br>
SDS HelpDesk Solutions v3.2 - Serial - P98638664195793 - (100 users) <br>
Seagate Backup Exec Enterprise - Adsm module +v7 for WinNT - s/n: 0244251786012345 - Autoloader module +v7.0 - s/n: 0542711783012345 - Disaster recovery +v7.0 - s/n: 0166671780012345 - Enterprise Editon +v7.0 for Win NT - s/n: 0243941784012345 - Exchange agent +v7.0 - s/n: 0070721788012345 - Migration utility +v7.0 - s/n: 0044741789012345 - Netware agent +v7.0 - s/n: 0170621787012345 <br>
Searchpad v1.0 - Name - Finn Mac CooL - Serial - BJ4819B (I think any name werks) <br>
SearchWolf v2.02 - Name - DanThaMan/fACTOR '98 - Serial - SE1998-201667 <br>
SearchWolf v2.03 - Nsme - #CRACKS - Serial - SE035-128815 <br>
SearchWolf v2.03 - Nsme - Finn Mac CooL - Serial - SE070-138114 <br>
SecureCRT v2.2.2 - Name - CRowmAN - Company - PC98 - Serial - 03-05-091998 - Expiration - Never - Key - 2703 3617 1285 8067 0249 <br>
SecureCRT v2.2.2 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 03-22-123123 - Expiration - Never - Key - 4584 7364 1145 5986 1154 <br>
SecureCRT v2.2.2 - Name - Phrozen Crew - Company - Phrozen Crew - Serial - 03-22-123123 - Expiration - Never - Key - 2340 8365 2858 2109 9652 <br>
SecureCRT v2.2.2 - Name - Zarkman - Company - [PC 98] - Serial - 03-22-123123 - Expiration - Never - Key - 0456 9648 3067 3605 8886 <br>
SecureCRT v2.2.3 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 03-22-230100 - Expiration - Never - Key - 4035 5360 2309 0715 1774 <br>
SecureCRT v2.2.3 - Name - CRowmAN - Company - PC98 - Serial - 03-14-101998 - Expiration - Never - Key - 1608 6170 7511 3348 4372 <br>
SecureCRT v2.2.3 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 03-22-111998 - Expiration - Never - Key - 4606 8917 7781 0156 4151 <br>
SecureCRT v2.3b1 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 03-22-230100 - Expiration - Never - Key - 4035 5360 2309 0715 1774 <br>
SecureCRT v2.3b1 - Name - CRowmAN - Company - PC98 - Serial - 03-14-101998 - Expiration - Never - Key - 1608 6170 7511 3348 4372 <br>
SecureCRT v2.3b3 - Name - - Company - PC98 - Serial - 03-05-091998 - Expiration - Never - Key - 2703 3617 1285 8067 0249 <br>
SecureCRT v2.3b3 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 03-28-019980 - Expiration - Never - Key - 5063 0500 1723 8563 6960 <br>
SecureCRT v2.3 - Name - - Company - PC98 - Serial - 03-05-091998 - Expiration - Never - Key - 2703 3617 1285 8067 0249 <br>
SecureCRT v2.3 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 03-28-019980 - Expiration - Never - Key - 5063 0500 1723 8563 6960 <br>
SecureCRT v2.3.1 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 03-28-019980 - Expiration - Never - Key - 5063 0500 1723 8563 6960 <br>
Secure Desk v3.0 - Serial - 3837453942553 <br>
Secure Explore v2.0 - Serial - 0368710729 <br>
Serv-U v2.4a - Put this in serv-u.ini under [Global] : Registrationkey=8uZTOvYb3a.,#CRACKS <br>
Serv-U v2.4a - Put this in serv-u.ini under [Global] : Registrationkey=SkX0sjSN9ls,PhRoZeN CReW '98 <br>
Serv-U v2.4b - Put this in serv-u.ini under [Global] : Registrationkey=8uZTOvYb3a.,#CRACKS <br>
Serv-U v2.4b - Put this in serv-u.ini under [Global] : Registrationkey=SkX0sjSN9ls,PhRoZeN CReW '98 <br>
ServerAdmin Plus v5.0 - Serial - F13-1234cc78901124672 <br>
Servers Unlimited Spider! v2.0 - First Name - (anything) - Middle Name - (anything) - Last Name - (anything) - (Your e-mail here) - Serial - 0000-00000 - Code - 4FFF-FFFFF <br>
Set Me Up 98 - Name - (Your name here) - Company - (Your company here) - Serial - smu <br>
Settlers 3 BETA - Serial - 1349-3583-1434-4345-4008 <br>
Setup Factory v4.07 - Serial - DRSF-1014 <br>
Setup Specialist 98 v2.0 - Name - Finn Mac CooL - Serial - ED0F67F3423238449B26FC29C38A5854 <br>
SFX-Factory! v1.5 - Name - Finn Mac CooL - Serial - 393-190-830 <br>
Share TheNet v2.05 - Serial - ovcnhaBoblhEmfjFQiMRFUJLFW <br>
ShareIt v2.02 - Name - Norway - Serial - SH8-117280 or SP8-184072 <br>
ShareIt v2.02 - Name - The_Gimp! - Serial - SH8-759806 or SP8-423864 <br>
Sheesh Fly v1.1 - Serial - SHEF9283 <br>
SideShow v1.0 - Serial - AJ500003 <br>
SideShow v1.1 - Serial - AJ500003 <br>
Simply Accounting v6.0 - Serial - 1021602-48016 <br>
Site/C v1.1 - Serial - RJC-3384077 <br>
Slides & Sounds Plus v2.0.0 (Build 149) - Credit card number - 00000000 - Serial - 2305298134434147 <br>
SLMail 3.1 Information Series #1 - Serial - 984827 - Auth Code - R-P3K7D-YW4WU-2JP8T <br>
Small Business Inventory Control v3.5 - Serial - 032598-300 <br>
SmartMaze v5.0 - Serial - 14348854002764 <br>
SmilerShell 95 v1.4 - Serial - C2640803876 or C2640103755 <br>
Snack WorkShop v1.20 - First Name - BLACK THORNE - Last Name - PC'98 - Serial - S68806739575-K1230 <br>
SnagIt v4.22 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 63A95856FFFFFFFF <br>
SnapShot v1.2 - Name - Finn Mac CooL - Serial - 2421P(37X) <br>
SNAPSHOT! Hockey Statistics Manager v1.36 - Serial - 019-089-911 (League License) <br>
SNAPSHOT! Hockey Statistics Manager v1.36 - Serial - 019-089-912 (Team License) <br>
Snapshot/32 v2.60 - Finn Mac CooL - Serial - 1860895283 <br>
SNTP v1.0 - Serial - xyzzy <br>
SocketWatch v2.0 - Serial - 8992-0014376 or 4307-0000690 or 4845-0008226 or 5817-0009792 or 3666-0016443 or 3898-0003264 or 8938-0018816 or 8229-0005841 or 5144-0023418 <br>
SocketWatch v3.0 - Serial - 8992-0014376 or 4307-0000690 or 4845-0008226 or 5817-0009792 or 3666-0016443 or 3898-0003264 or 8938-0018816 or 8229-0005841 or 5144-0023418 <br>
SocketWatch v3.1 - Serial - BLF-7362912 <br>
SoftiCE v3.22 Win 95/98 - Serial - 2110-00617F-77 <br>
SoftiCE v3.22 Win NT - Serial - 2210-004377-f3 <br>
SoftiCE v3.23 - Name - Finn Mac CooL - Serial - 1904-3345BB-BB <br>
SoftiCE v3.23 Win 95/98 - Serial - 1900-0000DD-9B <br>
SoftiCE v3.23 Win NT - Serial - 1800-0000DB-9B <br>
SoftiCE v3.24 Win 95/98 - Serial - 1900-713155-77 - url - http://216.49.10.245/ha/harvestr-webjump/si324w9x.zip <br>
SoftiCE v3.24 Win NT - Serial - 1800-71315F-77 - url - http://216.49.10.245/ha/harvestr-webjump/si324nt.zip <br>
SolSuite 98 v3.5 - Serial - 22021003 <br>
Start Menu Console Editor v1.0 - Name - Finn Mac CooL - Serial - 03011-546582 <br>
SoftImage v3.71 - Serial - SI-FB2323EA - Company Name - X-Force - Serial - D13-X86-2654-8314301D <br>
Solitaire v98a - Serial - 302625 <br>
SONIC v1.4 - Name - Finn Mac CooL - Serial - 0803 <br>
SONIC v1.6 - Name - Finn Mac CooL - Serial - 0803 <br>
Sound Forge v4.0 - Serial - 100-0000999-068550 <br>
Sound Forge v4.5 - Serial - 105-0000000-233806 <br>
Spam Killer v2.4 - Serial - 003E-9124-7E3E39 <br>
SpamEater Pro - Name - #CRACKS - Serial - $4973FF59 <br>
SpamEater Pro - Name - Finn Mac CooL - Serial - $BAB70985 <br>
SpeedyNet v4.22 - Name - Michelle L Serro - Serial - 99EA7 - Code - 294868 <br>
Speller for Microsoft Office v1.1 - Serial - Y7YUGYGUEEUUGS1205002 or 4PP44PP9W4P4P91605005 or 38S2ATA8ST2XS81805007 <br>
Spender Pro v2.0 - Serial - 15144DEE <br>
Splash v1.1 - Serial - NS-100-000-001 - Key - CCC8-2B1A <br>
SPSS v8.0 - ID - 281781 - Serial - 30865 10666 54452 79786 94805 8070 <br>
SPSS v8.0 - ID - 3327971 - Serial - 30616 56854 43021 45637 17664 4686 <br>
SPSS v8.0 - ID - 2141521 - Serial - 30155 67498 40203 25852 70186 1228 <br>
SQLabel v4.1 - Name - (Your name here) - Serial #1 - 3896857095 - Serial #2 - 852058377 <br>
Squizz v2.0 - Serial - 855022 <br>
Split32 v1.1 - Name - Finn Mac CooL - Serial - 1961533-S54 <br>
Splitty v1.6 - Serial - 18725032-01230567 <br>
Splitty v1.7 - Serial - 1872503201230567 <br>
Squizz v3.04 - Serial - ZQS202100207 <br>
SSSpider v1.05 - Serial - Q6CFHXVATDBW6SYFZWU2ZQK1JJTJW or MXZJ2KNLHB544H1THQQ2SVJGZ6ZBH <br>
StartCraft v1.03 - CD CdKey - 1234567890123 or 4835-08309-0407 or 2742-66220-2897 or 2942-46281-1002 <br>
Start Menu Changer '97 v2.60 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 4CF9C9D6 <br>
Start-It v4.01 - First Name - #CRACKS - Last Name - #CRACKS - Company - #CRACKS - Serial - 1598347758 <br>
Stay Connected v2.0 - Name - lxcore98 - Company - CORE - Serial - 8387F2598-5X66-9X873 <br>
Stay Connected v2.1 - Name - lxcore98 - Company - CORE - Serial - 8387F2598-5X66-9X873 <br>
StayOn Pro v2.5 - Serial - PRO-9805014455 <br>
StayOn Pro v2.61 - Serial - PRO-9805014455 <br>
StayOn Pro v2.7 - Serial - PRO-9805014455 <br>
Stealth Keyboard Interceptor Auto Sender v1.0 - Name - #CRACKS - Serial - 51091663 <br>
Stealth Keyboard Interceptor Auto Sender v1.0 - Name - Finn Mac CooL - Serial - 85CF6804 <br>
Stealth Keyboard Interceptor Pro v4.0 - Finn Mac CooL - Serial - 5D97C444 <br>
Stealth Keyboard Interceptor Pro v4.0 - TEX98 - Serial - E9DCEB2B <br>
Steinberg WaveLab v2.0 - Install Serial - Deepz0ne-Radium-1998-QCZ <br>
Steinberg WaveLab v2.0 - Install Serial - ST22-TBPK2P8-EPPNBY8-Y8BW (WinNT) <br>
Steinberg WaveLab v2.0 - Install Serial - ST22-TYB8YYY-EPPNBY8-Y4JH (Win95) <br>
StepUp 98 v4.08a - Name - Finn Mac CooL - Serial - 3581790368 (1 user) <br>
StepUp 98 v4.08a - Name - Finn Mac CooL - Serial - 631042848 (5 user) <br>
StepUp 98 v4.08a - Name - Finn Mac CooL - Serial - 2524296704 (50 user) <br>
StepUp 98 v4.08a - Name - Finn Mac CooL - Serial - 213393408 (500 user) <br>
StepUp 98 v4.08a - Name - Finn Mac CooL - Serial - 3496933937 (1000 user) <br>
StepUp 98 v4.08a - Name - Finn Mac CooL - Serial - 3081173553 (5000 user) <br>
Stickits Enhanced v96.7.20 - Serial - CYBERSTICKITS <br>
Stop Watch v2.2 - Name - Finn Mac CooL - Serial - 6A6-68D <br>
StormWindows v5.02 - Serial - 3225-2722-4439-9756 <br>
Stratos98 - Serial - ST123456789 - Code - 55530 <br>
Stream Weaver DVD Video Authoring Tool Pro v4.4 - Installation Serial - SW-15456 <br>
StreamWorks MP3 Server v3.10 Win95 - Serial - HE3A-7A1G-6A1A-1B5F <br>
StreamWorks MP3 Server v3.10 WinNT - Serial - HE3A-7A1G-6A1A-1B5F <br>
StripWav v2.03 - Name - Black Thorne - Code - 308831CFX <br>
Submit It v2.5 - Name - ASTAGA - Company - D4C - Serial - 257456038 <br>
SubmitWolf Pro v3.06 - Name - Anyone - Serial - PW1-180023 <br>
SubmitWolf Pro v3.08 - Name - Anyone - Serial - PW1-180023 <br>
SubmitWolf Pro v3.08 Script update - Serial - PW-F451F3- <br>
SubmitWolf v4.0 - Name - The Keyboard Caper - Serial - PE-597418 <br>
SUDS 97 - Name - Intern - Serial - SUDS1617 <br>
Super Edit v3.3 - Serial - 14xxx - (x = any number 1-9) <br>
Super Enalotto 2.0 - Name - (Your name here) - Serial - APE56FK2JW37VL <br>
SuperBase v4.0 - Serial - 302010051293 or 152010015966 <br>
SuperCat 2.1 - Name - Keefe Brooks - Serial - $069D6630 <br>
SuperFax v5.1 - Serial - 051212453 <br>
SuperJPG v2.2 - Name - Finn Mac CooL - Serial - 422400-15028238 <br>
SuperJPG v3.1 - Name - Finn Mac CooL - Serial - 123456-11865809 <br>
SuperMail v2.8b - Name - Finn Mac CooL - Serial - RKS-1444863 <br>
SuperPrint v4.0 - Serial - 400-400-xxxxx - (x = any number 1-9) <br>
SuperVoice v2.2 - Serial - 220006165 or 226104062 <br>
Support Magic v3.0 - Serial - 9128745234 <br>
SureStore Encryptor v2.2 - Name - DaVinci PC98 - Serial - fdrmfs9nhtkbpfvg <br>
Swell v97.3.11 - Serial - 123456789 - Code - 876543210 <br>
SyGate v1.21 - Serial - 646A4844-12149F53 - Code - 33738D88 <br>
SyGate v2.0 - Serial - 20012F9E-583EDBE4 - Code - 7C243D79 <br>
SyGate v2.0 - Serial - 46655206-1105CEB - Code - 8E918A08 <br>
SyGate v2.0 - Serial - 646A4844-12149F53 - Code - 33738D88 <br>
SyGate v2.0.320 - Serial - 40199709-565970 - Code - 1EEAFC0D <br>
SyGate v2.1 - Serial - 20012F9E-583EDBE4 - Code - 7C243D79 <br>
SyGate v2.1 - Serial - 46655206-1105CEB - Code - 8E918A08 <br>
Symon Says v1.0 - Serial - 384-PELZW-7246 <br>
SysBack v1.12 - Name - Finn Mac CooL - Serial - 715DEB787900 <br>
SysConfig98 v1.2 - Serial - 3E17FDB <br>
SysConfig32 v3.3b - Serial - 2c3c1936 <br>
System Commander Deluxe v4.0 - Serial - YC950084-ARAE or YC900773-RGFY or YF108537-AYEC or YF104807-KFKY <br>
System Commander Deluxe v4.02 - Serial - <br>
System Information Pro ActiveX v1.0 - Name - Finn Mac CooL - Serial - SIOCX-HHQAR-OMWST-SPFAQ <br>
System Information v1.8 - Serial - 2s4mp74hx <br>
Systran Personal v1.02 - Serial - <br>
Systran Professional v1.6 - Serial - SIVORY-ANDREW <br>
