Uninstall Manager v2.6 - Name - #CRACKS - Serial - 545 <br>
Uninstall Manager v2.6 - Name - Finn Mac CooL - Serial - 1076 <br>
Ultimate FileFinder v1.1 - Serial - LHFXGSVAB <br>
Ultimate Solitare v2.6 - Serial - 791582 <br>
Ultimate Language Tutor 4.3 761933 (nags only) <br>
Ultimate Solitaire: 791582 <br>
Ultimate Solitare Collection 2.5 791582 <br>
UltraEdit v5.21 - Name - Finn Mac CooL - Key - GIKEMENC35304430 <br>
UltraEdit v6.0 - Name - #CRACKS - Key - XCFWKWQD16230119 <br>
UltraEdit v6.0 - Name - Finn Mac CooL - Key - CDVGJFWQ14885869 <br>
UltraEdit v6.0a - Name - #CRACKS - Key - XCFWKWQD16230119 <br>
UltraEdit v6.0a - Name - Finn Mac CooL - Key - CDVGJFWQ14885869 <br>
Ultra Hal Assistant v1.0.91 - Serial - 72083REM <br>
Ultra Hal v6.0 - Serial - REM72083 <br>
Unios v1.9 - Serial - 16182088-09080700 <br>
Universal v1.5 Name - Plushmm [PC97] - Serial - 655162446 <br>
Universe Creator v1.6 - Name - MARQUIS UCF - Serial - 148999584 <br>
URL CLIPtomania v1.0 - Name - Black Thorne - PC'98 - Serial - SM3UPU48HOVD <br>
URL Spider v2.5.2 - Name - (Your name here) - Serial - IS2513- <br>
URL Spider v2.6.1 - Name - David Cowgill - Serial - 115364992477135589938 <br>
