Wallpaper v1.2 - Name - Finn Mac CooL - Serial - C41223D5 <br>
Wallpaper Manager 98 v1.13 - Serial - 847977-27701-011 <br>
Waste Whacker v2.12 - Name - Finn Mac CooL - Serial - 341082552666 <br>
Waste Whacker v2.12 - Name - The Master DaVinci - Serial - 500554744556 <br>
Waste Whacker v3.02 - Name - Warp98 - Serial - 489648749934 <br>
Waste Whacker v3.11 - Name - afdad [SpX] - Serial - 585259930016 <br>
Waterfall Pro v2.01 - Serial - 1797195037-8455-2754-5987 or 997334678-0373-5920-1968 <br>
Waterfall Pro v2.1 - Name - Finn Mac CooL - Serial - 30440097-2921-2832-0546 <br>
Waterfall Pro v2.1 - Name - Prophecy [tNO '98] - Serial - 22621938-2114-2953-5427 <br>
Waterfall Pro v2.1a - Name - Finn Mac CooL - Serial - 42038425-4112-9089-37 <br>
Wave Convert Pro v3.0 - Serial - 111-WPA9944 <br>
Wave Convert Pro v3.1 Build 4 - Name - (Your name here) - Company - (Your company here) - Serial - 10256 WP5020 A2670 <br>
Wave Events v2.0 - Name - X - Serial - TEX98 <br>
Wave Flow v2.0 - Login - #CRACKS - Password - 224683 <br>
Wave Flow v2.0 - Login - Black Thorne - PC'98 - Password - 2374701 <br>
Wave Flow v2.0 - Login - Finn Mac CooL - Password - 1203422 <br>
WaveStation v2.72 - Serial - WS27-1928-5634-1998 - Code - 254806749842 <br>
WaveStation v3.0 - Serial - WS3011-127868576225 <br>
Weather Online v1.0 - Serial - WO1WN5515 <br>
Weather1 v1.40.1.7 - Name - qwerty - Serial - U[IVX] <br>
Web Creator v1.0 - Name - Finn Mac CooL - Serial - 64701967 <br>
Web Expert v3.0 - Name - Finn Mac CooL - Serial - TZP45W-ACDSVL-XMQYE8-G4KW9C <br>
Web Extract ToolPak v1.0 - Serial - NS-100-000-015 - Key - 0600-F275 <br>
WEB Form Formatter v1.6 - Name - Finn Mac CooL - Serial - 794-7A7 <br>
Web Graphics Optimizer v4.0 - Name - Sn0wman - Company - none - City - heaven - Serial - WP1-208-036-308-997-0105-4176-784 <br>
Web Hacker 2.5 - Name #1 - Phrozen - Name #2 - Crew - Serial - 1368431568 <br>
Web Magician v1.0 - Serial - 847931526 <br>
Web Meta Power v1.0 - Serial - VFG-879-439 <br>
Web Phone v4.01 - Key - 4359NJ8PU124T852 or 747H86552V3453D0 or H925T842989AJ12D <br>
Web Phone v4.02 - Key - 4359NJ8PU124T852 or 747H86552V3453D0 or H925T842989AJ12D <br>
Web Plus v4.0 - Serial - ??nnnnwwnc?nnn?bvn?+++?n++?cw?n?cjfnfnf0n}p91 <br>
Web PriceList 2001 v1.3e - Name - ESCOM - Serial - RW3349218074957U - Code - ABCDEF <br>
Web Server 4D v2.02 - Serial - 88GE-VTSW-HFFF-GNGG <br>
Web Snap v2.2 - Serial - 69446532 <br>
Web Thumbnailer v1.2.3 - Serial - 787967-80027-012 <br>
Web Traffic Builder Pro v4.03 - Serial - WTB-ZVVWDLFZ <br>
WebBandit v3.60.01 - Serial - 197310 - Unlock - 972401 <br>
WebBoy v1.41 - Serial - WB10-01-12345678-nbfbqouagb or WB13-01-14031998-hdgbaiormd <br>
WebEdit PRO v3.0.4 - Name - Nop [Phrozen Crew] - Serial - F74EC7GA7271 <br>
WebEdit PRO v3.1 - Name - Mexelite'98 - Serial - F6F7DBFAC517 <br>
WebExpress v3.0 - Name - (Your name here) - Serial - 860-7105-735 <br>
WebExpress v3.0 - Name - Jan Henry Dickinson - Serial - 860-7105-735 <br>
WebFerret PRO v2.5101 - Serial - NS-100-002-267 - Key - 6304-1D8A <br>
WebFerret v2.7 - Serial - <br>
WebOverDrive v2.0 - Serial - $AE282254 <br>
Webpad v1.0 - Serial - I paid ;o) <br>
Webpass v4.0 - Serial - 1492 <br>
WebPop v2.01 for MDaemon - Serial - 102-01-02928-155-43556 <br>
WebSeeker v3.4.0.3 - Serial - WS2R-DWSXPU-7XWEE-E6L-8INWUG or WS2R-5ZFFBL-7XG2N-NVJ-NI3Q22 <br>
Webshop v3.41 - Serial - ILAB-472HPS3R <br>
Webshots Screen Saver Toolkit v1.05.2552 - Name - Finn Mac CooL - Key - WS1-FINNM - Serial - 4635-2415-5707-6505-8765 (Pro) <br>
Websnake v1.23 - Name - Phrozen Crew 98 - Serial - 123456789 - Reg Code - F1B148F5C3E900 <br>
WebSpider - Serial - GBU507130405066 (Standard) <br>
WebSpider - Serial - HO65730330175132029 (Pro) <br>
WebSurveyor v1.1.81 - Name - Finn Mac CooL - Serial - WSB-R0D3DD1B3717FF <br>
WebSurveyor v1.1.81 - Name - Finn Mac CooL - Serial - WSB-R0D3DD1B3717FF9 <br>
WebTwin v1.1a - Name - FreeKey 123456 - E-mail - FreeKey@hotmail.com - Serial - EEGZ-11-47217100 <br>
WebVCR v2.01 - Name - mpbaer - E-mail - mp@nowhere.com - Serial - 3d27-7773-k4dp-c6e7 <br>
WebVCR v2.02 - Name - xOANON - E-mail - xoanon@ucf.rulez.pc.sux - Serial - d8v4-svek-49ym-rvpf <br>
WebVCR v2.12 - Name - xOANON - E-mail - xoanon@ucf.rulez.pc.sux - Serial - d8v4-svek-49ym-rvpf <br>
WebWhacker v3.2.04 - Serial - WW2R-QQLJ7D-XAVK3-ITN-SHB4JG or WW2R-QCCB3S-XASBE-Z8M-YMHBJG or WW2R-YQNJ6T-XWJXX-VGS-5SWYWG or WW2R-QZ38CK-KA2KV-KI8-REG4J2 or WW2R-QQ4WD6-XA42P-WAB-VXFCVG or WW2R-H3D3MR-XP8GM-FDE-JQPNBG <br>
WebWolf v1.04 - Name - Finn Mac CooL - Serial - WW1-212223 <br>
Webzip v2.41 - Name - Finn Mac CooL - Serial - 5ADBAC34FA3E499 <br>
Webzip v2.45 - Name - Finn Mac CooL - Serial - 5ADBAC34FA3E499 <br>
Webzip v2.47 - Name - Finn Mac CooL - Serial - 5ADBAC34FA3E499 <br>
Webzip v2.50 - Name - Finn Mac CooL - Serial - 5ADBAC34FA3E499 <br>
WetSock v3.8b - Serial - WSI-2915820 <br>
WhatColor v2.4e - Serial - 56770115 <br>
Where Is It v2.0 - Name - David J Tominsek - Company - Private - Serial - 012215-100-42887 - Code - LAfDf3T6A7LZ6QSuyH0gnAyC0hFs7vOgsgIoB2r3 <br>
Win 95 (floppy Install) - Serial - 34297-OEM-0028396-13817 <br>
Win NT v4.0 - Serial - 040-0585782 or 040-0662678 or 040-0764476 <br>
Win Patch v1.2 - Name - (Your name here) - Company - (Your company here) - Serial - Art+Debby+Daisy+Lucy!@ <br>
Win Patch v1.2 - Name - Finn Mac CooL - Company - #CRACKS - Serial - L&D-611-84052649 <br>
Win Proxy v2.1 - Unlimited Users - Serial - 1001-00000023-383 or 1255-C9YKLH4O-278 or 1960-CCKQCP8Q-076 or 1665-HKP7XQ1F-250 <br>
Win98 Upgrade Serial - G2FGT-6HYRW-X2W2C-RT7HW-RF7WX or R4WW8-7HXF6-QFW99-WVB2G-4BP42 or HGBRM-RBK3V-M9FXV-YCXDK-38J4 <br>
Winamp v2.02 - Name - Finn Mac CooL - Serial - 47173473 - url - www.winamp.com <br>
Winamp v2.02 - Name - Phrozen Crew 98 - Serial - 13697215 - url - www.winamp.com <br>
Winamp v2.05 - Name - #CRACKS - Serial - 91580515 - url - http://winamp.com/download/locations.html <br>
Winamp v2.06 - Name - #CRACKS - Serial - 91580515 - url - http://winamp.com/download/locations.html <br>
Winamp v2.09 - Name - Finn Mac CooL - Serial - 47173473 - url - http://winamp.com/download/locations.html <br>
WinAnalyzer v1.01 Name - (Your name here) - Serial - 0401-0012344 <br>
WinArj 98 v4.10 - Name - #CRACKS - Serial - 33857765628765 <br>
WinArj 98 v4.10 - Name - KEIOS@LEAF - Serial - 07756966746389737965 <br>
WinBoost 98 v1.0 - Name - Sonixx - Serial - 426952673 <br>
WinBoost 98 v1.1 - Name - Sonixx - Serial - 426952673 <br>
WinBoost 98 v1.2 - Name - #CRACKS - Serial - 299375188 <br>
WinBoost 98 v1.2 - Name - Finn Mac CooL - Serial - 658311703 <br>
WinBoost 98 v1.2 - Name - Sonixx - Serial - 426952673 <br>
WinBoost 98 v1.23 - Name - #CRACKS - Serial - 299375188 <br>
WinBoost 98 v1.23 - Name - Finn Mac CooL - Serial - 658311703 <br>
WinCD v1.5 - Name - frenzy - Serial - 25045 <br>
WinChime v2.4 - Name - xOANON - Serial - 8C66B6B77 <br>
WinDac v1.47 ->> http://members.aol.com/schmelnik/wdac147.zip (Name = Free Version Serial = BIX4GUEUTIAIUPYY) <br>
WinDates v3.7 - Name - Finn Mac CooL - Serial - 07664753 <br>
WinDownload v4.0 - Name - Finn Mac CooL - Serial - 30974756117148843 <br>
Windows 98 Dutch - Serial - qcwjd-f94yq-kwqxx-m48m3-mcfqw <br>
Windows 98 German - Serial - HK6PD-2QBPV-4RCXY-KRPWT-DM346 <br>
Windows 98 International - Serial - MD97J-QC7R7-TQJGD-3V2WM-W7PVM <br>
Windows 98 Italian - Serial - JR36V-BDGVC-64PT2-WB66P-D64 <br>
Windows 98 OEM - Serial - DKRBQ-TXYCX-6K4GD-4CPJ7-C6B26 or FT9CH-XVXW7-7BFCM-RPR49-VDHYD or PW3DW-PC9D8-Q7VMQ-8YTMY-RTR9G or M4G3G-77CGM-9FY8T-PMWBC-JJYDM or FQYYM-MGGJ7-3J69K-RVQ4T-W8HCH <br>
Windows 98 OEM SR1-B1 - Serial - C9TCH-G72Y6-G4DQK-QCQRM-K7XFQ <br>
Windows 98 Retail - Serial - K4HVD-Q9TJ9-6CRX9-C9G68-RQ2D3 or QY84Q-QT6QF-GJMGY-MFT4Y-RCBWG or PTX6T-WTQ9G-C7B2Y-TC3K8-YT4GB <br>
Windows Grep v2.1.1123 - Serial - 1675270417 <br>
Windows NT Cd-Keys - Serial - 811-7443012 or 811-1380196 or 811-1379413 <br>
Windows NT Workstation 4.0 - OEM Serial - 09496-OEM-0009552-77303 or 30495-OEM-0006276-08164 or 20796-OEM-0013791-67471 <br>
Windows Lotto v4.04 - Name - GREENBACK - Serial - F7F7556C86E76 <br>
Windows Task-Lock v4.1 - Serial - 418117113408700703414174 <br>
Windoze v1.41 - Name - #CRACKS - Serial - 22-34-41-37-39-44-48 <br>
WinEdt32 v1.414 - Name - Denis Grondin - Serial - 38477750 <br>
Win-eXpose-IO v2.0 - Serial - 92346556 - Code - f40cdce2 <br>
WinFit v2.0 - Serial - 0206881241 or 0206881254 or 1006775544 <br>
WInfo View v2.0 - Name - bUrnoUt - Serial - 209349220464 <br>
WINFO Viewer v2.0 - Name - ASTAGA [D4C] - Serial - 112264130372 <br>
Wingate Pro v2.1d - Name - Finn Mac CooL - Serial - 9A7C0848C259184E6DA9ABED - Unlimited Users <br>
Wingate Lite v3.0 - Name - Finn Mac CooL - Serial - 9A7C08482707184EAEA99F6D - Unlimited Users <br>
Wingate Pro v3.0 - Name - Finn Mac CooL - Serial - A97C08484569184EFDA9946D - Unlimited Users <br>
WinGrep v2.1 - Serial - 656C7669732F <br>
WinHack v1.10 - Name - Finn Mac CooL - Serial - G8D-9873-14805 <br>
WinHacker 95 v2.02 - Name - Clark Kent - Company - Daily Planet - Serial - f023-1581c7 <br>
WinImage v4.0 (Pro Mode) - Name - Finn Mac CooL - 1ACF21FA <br>
WinImage v4.0 (Stantard Mode) - Name - Finn Mac CooL - ACA0B79 <br>
WinImages v4.5 - Alpha - Serial - 7620-5405-0635-1061 <br>
WinImages v4.5 - Art - Serial - 2666-6871-1753-4382 <br>
WinImages v4.5 - Attrib - Serial - 5571-2224-8340-7784 <br>
WinImages v4.5 - Blur - Serial - 0086-7112-7223-2238 <br>
WinImages v4.5 - Collage - Serial - 3368-0110-4648-1073 <br>
WinImages v4.5 - Filter - Serial - 4485-0860-7848-2457 <br>
WinImages v4.5 - Geom - Serial - 6083-5362-8546-3208 <br>
WinImages v4.5 - Lighting - Serial - 1657-6021-5842-5257 <br>
WinImages v4.5 - Math - Serial - 8342-3342-1314-6348 <br>
WinImages v4.5 - Morph - Serial - 4133-7108-2438-8242 <br>
WinImages v4.5 - Pattern - Serial - 6083-0806-7388-4247 <br>
WinImages v4.5 - Photo - Serial - 3043-0300-5057-4863 <br>
WinImages v4.5 - Plasma - Serial - 0386-2352-0363-3724 <br>
WinImages v4.5 - Standard - Serial - 7005-2446-0771-8453 <br>
WinImages v4.5 - Video - Serial - 3715-5274-0553-0760 <br>
WinJammer Pro v5.0 - Name - <br>
WinJammer v3.0 - Name - Finn Mac CooL - Company - Fee Free Warez - Serial - 5HQQ5A4 <br>
WinKey Disable v1.0.1 - Name - X - Serial - 0 <br>
WinLog 98 v3.5 - Name - Finn Mac CooL - Company - #CRACKS - Serial - 33651596536821 <br>
WinNC v1.5 - Name - Finn Mac CooL - Company - (Your company here) - Serial - FJPDMiUH5q <br>
WinOnCD ToGo! v4.5 - Serial - 01423-94070446m <br>
WinOnCD v3.5 - Serial - 01146-51863460v or 01146-99077920o <br>
WinOnCD v3.6 - Serial - 01510-30673562k or 01551-06845806o <br>
WinPac2 v1.x - Name - Finn Mac CooL - Serial - 63778-34900-08281-34718 <br>
WinPlay v2.0 - Serial - 100011-301000-5000 or 222221-025226-0222 or 847013-739958-2B26 or 199610-939817-9997 <br>
WinPop Plus v1.31 - Name - Finn Mac CooL - Serial - 12710B00 <br>
Winpop Plus v1.31 - Name - Finn Mac CooL - Serial - 0F767532 (Pro) <br>
WinQoole 2.5 - Name - Hack Section - Serial - 8767VJ-6890JJ-0971ML-7814XZ <br>
WinRAR v2.04 - Name - Finn Mac CooL - Serial - 9F915BFE69BBEE <br>
WinRAR v2.05 - Name - Finn Mac CooL - Serial - 9F915BFE69BBEE <br>
WinRAR v2.05 - Name - The Krazy Nomad [DEViANT] - Serial - 0A2A2B9DB2FC81 <br>
WinRAR v2.06 - Name - Finn Mac CooL - Serial - 9F915BFE69BBEE <br>
WinRescue95 v8.03 - Serial - msR3I8aUi9y2E84L <br>
WinRescue98 v3.02 - Serial - SvetCHRISTA <br>
WinRoute v3.0 - Serial - <br>
WinSecure v1.9 - Name - Culosucio - Serial - 3082538249 <br>
WinSecure v1.9 - Name - Spider] - Serial - 489766086195WSNS <br>
WinSecure v2.0 - Name - Spider] - Serial - 489766086195WSNS <br>
Win-Secure it v2.0 - Serial - DURK - Password - dc6144b4 <br>
Winshade v3.01 - Name - #CRACKS - Serial - 11111111010102DB <br>
Winshade v3.01 - Name - Finn Mac CooL - Serial - 111111110101046A <br>
Winshade v3.01 - Name - Plushmm PC - Serial - 11111111010103DA <br>
Winsock Swapper v1.7 - Name - Finn Mac CooL - Serial - 2843,PBS,7* <br>
WinSplit v3.03 - Serial - WIN-SPLIT-3002 <br>
WinStock PRO v2.31 - Name - UNICITY - Serial - 115-97-88-50-99-100 <br>
WinWhatWhere Investigator v1.0 - Name - Famous Computer Journalist (1 User) <br>
WinWhatWhere Investigator v1.0 - Name - World Renowned Editor (10 Users) <br>
WinXFiles v3.4 - Name - DarkGrey - Serial - RKHEVZBZHUWRQUP <br>
Winzip v6.3 - Name - #CRACKS - Serial - A4A3061F - Self-Extractor - Serial - 223507 <br>
Winzip v6.3 - Name - Finn Mac CooL - Serial - F4EC1991 - Self-Extractor - Serial - 699430 <br>
Winzip v7.0 - Name - #CRACKS - Serial - A4A3061F - Self-Extractor - Serial - 223507 <br>
Winzip v7.0 - Name - Finn Mac CooL - Serial - F4EC1991 - Self-Extractor - Serial - 699430 <br>
Wise InstallMaster v7.01 - Serial - 734-1000481 <br>
WiT v5.2 Pro sp2 - Serial - 14095000000000000000 <br>
Wizguard v1.25 - Serial - 4561-5130-0012-5075:VJ42 <br>
Workstation Lock Ver 2.6 - Serial - 2465535864435543654 (Single) <br>
Workstation Lock Ver 2.6 - Serial - 5735435434154321554 (Site) <br>
World Watch 3.1 - Serial - 008-2432449 or 027-7471620 or 000-8663454 or 522-3227058 <br>
WPlay v1.6 - Serial - KAGI-13320A1C-DBAEDDD059B5FC22 or KAGI-5A323825-1F5D161E909B0C5F or KAGI-67321234-6789DAB809155991 or KAGI-AD32AE24-8879250A62084B8E or KAGI-803292BA-17A7955560D069BB <br>
WPlay v1.7 - Serial - KAGI-13320A1C-DBAEDDD059B5FC22 or KAGI-5A323825-1F5D161E909B0C5F or KAGI-67321234-6789DAB809155991 or KAGI-AD32AE24-8879250A62084B8E or KAGI-803292BA-17A7955560D069BB <br>
WPlay v1.7b3 - Serial - KAGI-66323DDC-F2E5EFFADA51A32A <br>
WS_Ping ProPack v2.1 - Serial - WP-101175 <br>
WWW Gif Animator v1.1 - Finn Mac CooL - Serial - 564169 <br>
