Zip Assistant v4.0 - Serial - ORACLE32 <br>
Zip Clean v1.65 - Name - Finn Mac CooL - Serial - 1279259160 <br>
Zip Explorer PRO v2.54 - Name - (Your name here) - Serial - 1-42-12345-789 <br>
ZipLabel v4.1 - Name - (Your name here) - Serial #1 - 3896857095 - Serial #2 - 852058377 <br>
Zip98 Plus v3.0 - Name - Crowman /98 - Serial - 4221512D <br>
Zip98 Plus v3.0 - Name - TheBrabo - Serial - 65086457 <br>
ZipBackup v1.8 - Password - J279Y56 <br>
ZipCat PRO v3.008 - Serial - FZ3-F6J-6314713599 or BZY-4ZT-8395045441 <br>
ZipTest v3.06 - Name - TheBrabo - Serial - 7409326873 <br>
ZipTest v3.29 - Name - Finn Mac CooL - Serial - 2390270160 <br>
ZipTest v3.29 - Serial - 9181891179 <br>
ZipWorks v2.6 - Name - Finn Mac CooL - Serial - 721,*,P37122 <br>
zMUD v5.44b - Name - ABC - Serial - 071445366413 <br>
ZOC v3.10 - Press Ctrl-Alt-Shift and F9 at the same time then enter - A - 16434/01165/20785 - B - 25807 <br>
