<TABLE width="700" border="0" bgcolor="#cccccc"  bordercolor="#000000" align="center" cellpadding="0" cellspacing="0">
<TR>
<TD background="buttonbrn.gif" align="center" width="100"><A href="index.php" target="">[Algus]</A></TD>
<TD background="buttonbrn.gif" align="center" width="100"><A href="mina.php" target="">[Mina]</A></TD>
<TD background="buttonbrn.gif" align="center" width="100"><A href="mp3.php" target="">[Mp3]</A></TD>
<TD background="buttonbrn.gif" align="center" width="100"><A href="programmid.php" target="">[Download]</A></TD>
<TD background="buttonbrn.gif" align="center" width="100"><A href="max.php" target="">[Max]</A></TD>
<TD background="buttonbrn.gif" align="center" width="100"><A href="doom.php" target="">[Doom]</A></TD>
<TD background="buttonbrn.gif" align="center" width="100"><A href="special.php" target="new">[Specia]l</A></TD>
</TR>
</TABLE>