<TABLE width="70%" height="1" border="1" bordercolor="#000000" cellspacing="0">
<TR>
        <TD>Ikoon</TD>
        <TD>Nimi</TD>
        <TD>Kirjeldus</TD>
        <TD>Suurus</TD>
</TR>
<TR><TD><IMG src="htmlicon.gif"></TD>
        <TD>JimHtmlEditor</TD>
        <TD>Ise tehtud html editor(sisaldab Ftp klienti)</TD>
        <TD>~100KB</TD>
</TR>
<TR>
        <TD><IMG src="adawaret.gif"></TD>
        <TD><A href="aaw.exe" target="">Ad-Aware 5.83</A></TD>
        <TD>Programm arvutist spyware eemaldamiseks</TD>
        <TD>871KB</TD>
</TR>
</TABLE>
