<?php

/*
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first 7 triangle numbers:

 1: 1
  3: 1,3
  6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28

We can see that the 7th triangle number, 28, is the first triangle number to have over five factors.

Which is the first triangle number to have over five-hundred factors?

Solution by Raivo Laanemets
27th December 2004
*/

$c=0;
$x=0;
$th=1;
$eps=0.00001;
while ($c<5) {
	$x+=$x+1;
	
	echo $th .": ";
	
	//factorize
	$remain=$x;
	$div=1;
	while ($remain>1) {
		$acc=$remain/$div;
		if ($acc-floor($acc)<$eps) { $remain=$acc; echo $div .", "; }
		$div++;
	}
	
	echo $x ."\n";
	
	$th++;
}

echo $term ."\nReady\n";

?>