doc:
	rm -rf srcdoc
	mkdir srcdoc
	docsrc misjonarid.pl 'Misjonäride probleemi lahendaja'
	docsrc misjonarid_http.pl 'Veebiliides'
	docsrc misjonarid_server.sh 'Veebiliidese käivitaja'
	docsrc_index srcdoc