install:
	rm -rf /usr/local/k8055
	mkdir /usr/local/k8055
	cp src/Controller.py /usr/local/k8055/Controller.py
	cp src/K8055Controller.py /usr/local/k8055/K8055Controller.py
	cp start.sh /usr/local/bin/k8055d
	chmod +x /usr/local/bin/k8055d